### ISSUE TITLE
Disable logging by default

### ISSUE THREAD

**Issue by nichtich** [citation-js/citation-js#10]
How can I disable all that noise printed to stderr? Even a `require('citation-js') emits

~~~
[set] Subclass "@bibjson/quickscrape+record+object" is waiting on parent type "@bibjson/record+object"
[set] Subclasses "@bibjson/quickscrape+record+object" finally registered to parent type
~~~

I'd prefer disabled logging by default and enabling with an environment variable (can be set in `.env` with dotenv package).

**Comment by larsgw** [comment]
I thought I pinned an issue for this already. This is on my TODO-list, I don't like it either but I want to set up a good replacement. I'm planning to work on Citation.js again next week, I've quite some stuff to do this week and the past few weeks. I also plan to finish at least some of the cache then.

In the meantime, a temporary workaround: setting the environment variable `TEST_MOCHA=true` should work. This itself is a dirty hack. I'll look at dotenv.

**Comment by larsgw** [comment]
Now you can turn it up with `Cite.logger.level` (`silent`, `error`, `warn`, `info`, `debug`, `http`). Also, it doesn't pollute the global namespace anymore).
