### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by tsikerdekis** [citation-js/citation-js#101]
This is a peculiar error that I cannot figure out why it is generated. I have the code and the log. It seems to me that the id exists in the cite object. Any ideas?

Code that generated the error:
`cit = Cite(data[key])
citation = cit.format('citation', { template: 'apa', lang: 'en-US' })`

Error log with objects printed:
`  @article{tsikerdekis2014online, author={Tsikerdekis, Michail and Zeadally, Sherali}, title={Online deception in social media}, year={2014}, journal={Communications of the ACM}, volume={57}, number={9}, pages={72--80}, }
>  Cite {
>    _options: {},
>    log:
>     [ [ '[{"author":[{"given":"Michail","family":"Tsikerdekis"},{"given":"Sherali","family":"Zeadally"}],"title":"Online deception in social media","container-title":"Communications of the ACM","volume":"57","issue":"9","page":"72-80","type":"article-journal","citation-label":"tsikerdekis2014online","id":"tsikerdekis2014online","year-suffix":"online","issued":{"date-parts":[["2014"]]},"_graph":[{"type":"@bibtex/text","data":"@article{tsikerdekis2014online, author={Tsikerdekis, Michail and Zeadally, Sherali}, title={Online deception in social media}, year={2014}, journal={Communications of the ACM}, volume={57}, number={9}, pages={72--80}, }"},{"type":"@else/list+object"},{"type":"@bibtex/object","data":{"type":"article","label":"tsikerdekis2014online","properties":{"author":"Tsikerdekis, Michail and Zeadally, Sherali","title":"Online deception in social media","year":"2014","journal":"Communications of the ACM","volume":"57","number":"9","pages":"72–80"}}},{"type":"@csl/list+object"}]}]',
>         '{}' ] ],
>    data:
>     [ { author: [Array],
>         title: 'Online deception in social media',
>         'container-title': 'Communications of the ACM',
>         volume: '57',
>         issue: '9',
>         page: '72-80',
>         type: 'article-journal',
>         'citation-label': 'tsikerdekis2014online',
>         id: 'tsikerdekis2014online',
>         'year-suffix': 'online',
>         issued: [Object],
>         _graph: [Array] } ] }
>  TypeError: Cannot read property 'id' of undefined
>      at CSL.Disambiguation.getCiteData (/home/user/Dropbox/web/functions/node_modules/citeproc/citeproc_commonjs.js:23940:37)
>      at CSL.Disambiguation.initVars (/home/user/Dropbox/web/functions/node_modules/citeproc/citeproc_commonjs.js:23829:10)
>      at CSL.Disambiguation.run (/home/user/Dropbox/web/functions/node_modules/citeproc/citeproc_commonjs.js:23413:14)
>      at CSL.Registry.setdisambigs (/home/user/Dropbox/web/functions/node_modules/citeproc/citeproc_commonjs.js:22815:33)
>      at CSL.Engine.updateItems (/home/user/Dropbox/web/functions/node_modules/citeproc/citeproc_commonjs.js:9053:19)
>      at citation (/home/user/Dropbox/web/functions/node_modules/@citation-js/plugin-csl/lib/citation.js:23:12)
>      at format (/home/user/Dropbox/web/functions/node_modules/@citation-js/core/lib/plugins/output.js:53:28)
>      at Cite.format (/home/v/Dropbox/web/functions/node_modules/@citation-js/core/lib/Cite/get.js:21:29)
>      at generateCitation (/home/user/Dropbox/web/functions/util/citationHelper.js:96:24)
>      at db.doc.get.then.then (/home/user/Dropbox/web/functions/handlers/citations.js:164:29)
`

**Comment by larsgw** [comment]
I am not able to find this error when I [run your code](https://runkit.com/larsgw/citation-js-gh-101). However, there might still be an error since this does not reproduce your complete environment. What version of Citation.js are you using? If you are using `0.5.0-alpha.7` right now, could you try `0.5.0-alpha.6`?

**Comment by tsikerdekis** [comment]
I can confirm that it works on `0.5.0-alpha.6`.I was using `0.5.0-alpha.7`.

**Comment by larsgw** [comment]
Then it's likely a regression in https://github.com/citation-js/citation-js/commit/efa648ba570de7dabf0651442ca8ffdf52fcd5fe. The error might be caused by calling `.format()` sequentially on items with the same ID, though I cannot confirm that right now.

**Comment by larsgw** [comment]
It would be very helpful to have a minimal code example that reproduces the error, do you think you could provide that?

**Comment by tsikerdekis** [comment]
Here is the code that generates the error for alpha7

`const Cite = require('citation-js')

function generateCitation (data, citationStyle, note = []) {
  let result
  // Even if a single citation is given, convert to an array
  if (!Array.isArray(data)) {
    data = [data]
  }

  for (const key in data) {
        cit = Cite(data[key])
        citation = cit.format('citation', { template: citationStyle, lang: 'en-US' })
      }

  return result
}

data = ['@Article{tsikerdekis2014online, author={Tsikerdekis, Michail and Zeadally, Sherali}, title={Online deception in social media}, year={2014}, journal={Communications of the ACM}, volume={57}, number={9}, pages={72--80}, }',
'@article{tsikerdekis2014multiple, author={Tsikerdekis, Michail and Zeadally, Sherali}, title={Multiple account identity deception detection in social media using nonverbal behavior}, year={2014}, journal={IEEE Transactions on Information Forensics and Security}, volume={9}, number={8}, pages={1311--1321}, }']

generateCitation(data, 'apa')

`

**Comment by larsgw** [comment]
Thank you, that works (or rather doesn't, I guess). I am working on a fix.

**Comment by larsgw** [comment]
I published the fix in `0.5.0-alpha.8` (and `0.5.0-alpha.9` gets rid of a dependency warning). Does that work?
