### ISSUE TITLE
Breaks Safari

### ISSUE THREAD

**Issue by silencesys** [citation-js/citation-js#120]
Citation.js breaks site rendering in Safari as it seems it uses backward regex search which is not implemented in Apple's browser. 

This line: https://github.com/citation-js/citation-js/blob/9564b343657f737e7996591171330013bfb50c3c/packages/plugin-bibtex/src/output/value.js#L89

**What version of Citation.js are you using?**
0.5.0-alpha.10

**How are you running Citation.js (npm package, browser bundle, self-rolled bundle, webpack)?**
Installed with npm, built with webpack - part of Nuxt.js application

**Where are you running Citation.js?** _* The OS usually will not matter much, but the browser really does._
Safari 14.0.3

**What is your input data and code?**
My input data are formatted in BibTex, however I can pass pretty much anything and it will result in error.

**What did you expect to happen, and what actually happened?**
Safari should not complain about regex error.

**Comment by larsgw** [comment]
Thank you for reporting this. I do not remember whether I thought the code transformer would pick up on this but it does not. I will check it out.

**Comment by silencesys** [comment]
Thanks, I wish I could help, but regex is not my domain. 🙈

**Comment by larsgw** [comment]
It'll be in the next release, I just want to check if I can fix the docs. If JSDoc (for monorepos) happens to be your domain, let me know :slightly_smiling_face:

**Comment by larsgw** [comment]
Also, thank you for using the bug template! I haven't seen that one in a while.
