### ISSUE TITLE
`Invalid Regular expression` bug on Safari

### ISSUE THREAD

**Issue by danieleguido** [citation-js/citation-js#122]
Hello and first of all thank you for this great lib! 

I am using the version `0.5.0-alpha.10` of Citation.js in a react app (so as npm package) to publish articles for a new web journal. I'm testing it on Chrome, Firefox and Safari.

I bumped into a weird behaviour on Safari, which I've reproduced in a simple react app at https://codesandbox.io/s/quizzical-worker-9j6wq?file=/src/App.js. This small app works if you open it on Chrome or Firefox, but it fails on Safari.
It seems like the `Cite#format()` function doesn't work properly as it throws:

```
SyntaxError
Invalid regular expression: invalid group specifier name
```

Is there any simple solution?

This is the code I'm using:

```jsx
const reference = new Cite({
    "ISBN": "1-84467-185-2",
    "author": [{"family": "Moretti","given": "Franco"}],
    "id": "7009778/TSIQRMTK",
    "issued": {"day": 17,"month": 9,"year": 2007},
    "number-of-pages": "119",
    "publisher": "Verso",
    "shortTitle": "Graphs, Maps, Trees",
    "title": "Graphs, Maps, Trees: Abstract Models for Literary History",
    "title-short": "Graphs, Maps, Trees",
    "type": "book"
})
const referenceAsHTML = reference.format('bibliography', {
    template:'apa',
    format:'html',
})
```

**Comment by larsgw** [comment]
A similar error was reported recently (#120), I am looking to see if it is the same problem.

**Comment by larsgw** [comment]
Thank you for reporting this. As far as I can see it is the same error, which I will try to release today.

> ```js
>     "issued": {"day": 17,"month": 9,"year": 2007},
> ```

Where did you get this CLS-JSON? That line should be something like:

```js
    "issued": { "date-parts": [2007, 9, 17] },
```

**Comment by danieleguido** [comment]
Hi @larsgw, I've just upgraded to 0.5.0 and it works like a charm, thank you! 
Actually that JSON comes from Zotero via the [cite2c](https://github.com/takluyver/cite2c) extension for jupyter notebook, so it's a litte bit complicated to tell where, why and how the CLS-JSON changed.
