### ISSUE TITLE
Copy to clipboard a bibliography in rich text formating

### ISSUE THREAD

**Issue by khoivan88** [citation-js/citation-js#124]
Hi,

First of all, thank you very much for this package. I successfully set up this as part of a workflow using a static site generator (11ty) to build an academic website. Specifically, a list of DOIs is fed through citation.js and the output (in HTML format) is used for the build process of the publication page. That all works really well 😄 !!

I have also recently discovered this website from Zotero https://zbib.org/ and I think the Export/Copy to clipboard using the Rich Text Format is really cool (screenshot below). I was just wondering if it is possible to use citation.js in my same workflow to output a rich-text format of the bibliography item? I can take care of all of the creating button and/or copy to clipboard but stuck on how to convert to a rich text format. I was wondering if you might be able to help me or maybe point me in the right direction?
![image](https://user-images.githubusercontent.com/33493502/116261754-f3cfdc80-a745-11eb-91d5-de1278f28821.png)

Thank you very much!

**Comment by larsgw** [comment]
That's great to hear! RTF is supported in citeproc-js, so it is available for formatted bibliographies in Citation.js:

```js
const Cite = require('citation-js')

Cite('10.1234/doi').format('bibliography', {
  format: 'rtf'
})
```

**Comment by khoivan88** [comment]
wow, so simple, I will have to try it at some point. Thank you so much for your quick reply. If this work, I wonder if I should have this info (the RTF for the citation) ready from the build process or defer it as javascript on the client side. Regardless, this is really cool. Thank you so much @larsgw !!

**Comment by khoivan88** [comment]
It works like a champ!! Thank you very much! However, I ended up not using that because I didn't want to do a sever-rendering of the RTF for bibliography. I ended up using this library https://github.com/lgarron/clipboard-polyfill to render and copy into clipboard the RTF of the div of the bib on the client-side. Anyway, still, thank you so much for your help !! 😄
