### ISSUE TITLE
`Uncaught ReferenceError` on loading `citation-js` in production

### ISSUE THREAD

**Issue by berger-n** [citation-js/citation-js#128]
in our React app calling ` Cite = require("citation-js")` works perfectly in development mode, but fails in production after building & deploying app: 

![image](https://user-images.githubusercontent.com/33383857/124610819-1e8a8f80-de71-11eb-9f46-a5b534d67172.png)

app is currently deployed and tested here: http://library-dev.bdrc.io/show/bdr:W22084

(error message is available at the top of the error console 
I managed to delay loading `citation-js` so as app can load
otherwise it crashed upon the error)

**Comment by larsgw** [comment]
Thank you for the report, I will look into it ASAP.

**Comment by larsgw** [comment]
Weird, it looks like something is going wrong in the minification process, specifically of the [`moo`](https://www.npmjs.com/package/moo) dependency. The `reGroups` function is inlined but the arguments aren't renamed properly. What are you using for minification?

---

## Details

Normally, the code that is erroring looks like this:

```js
function reGroups(s) {
    var re = new RegExp('|' + s)
    return re.exec('').length - 1
}
```

```js
// convert to RegExp
var pat = reUnion(match.map(regexpOrLiteral))

// validate
var regexp = new RegExp(pat)
if (regexp.test("")) {
    throw new Error("RegExp matches empty string: " + regexp)
}
var groupCount = reGroups(pat) // (1)
if (groupCount > 0) {
    throw new Error("RegExp has capture groups: " + regexp + "\nUse (?: … ) instead")
}
```

https://github.com/no-context/moo/blob/v0.5.1/moo.js#L227-L238

The line marked `(1)` is the line that produces the error, and it looks like this after minification:

```js
var _ = o(g.map(a))
  , x = new RegExp(_);
if (x.test(""))
    throw new Error("RegExp matches empty string: " + x);
var w = new RegExp("|" + s).exec("").length - 1; // (1)
if (w > 0)
    throw new Error("RegExp has capture groups: " + x + "\nUse (?: \u2026 ) instead");
```

Again, `(1)` is the same line. Except

**Comment by berger-n** [comment]
> Weird, it looks like something is going wrong in the minification process, specifically of the [`moo`](https://www.npmjs.com/package/moo) dependency. The `reGroups` function is inlined but the arguments aren't renamed properly. What are you using for minification?

the build is made using `react-scripts build` default configuration, do you want to know something more? 
I'll upgrade this to latest version to see if it changes anything.

thanks for the quick reply!

**Comment by berger-n** [comment]
thanks a lot @larsgw! upgrading `react-scripts` fixed the bug.

**Comment by larsgw** [comment]
Great to hear!
