### ISSUE TITLE
Avoid need for 'unsafe-eval' in Content-Security-Policy.

### ISSUE THREAD

**Issue by jlaasonen** [citation-js/citation-js#138]
We're using citation-js in the browser and are running into issues with our strict [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src) blocking unsafe evaluation of JavsScript. This appears to be caused by dependency on [moo](https://github.com/no-context/moo) which uses unsafe evaluation for optimization purposes. See the issue https://github.com/no-context/moo/issues/141.

`'unsafe-eval'` in `script-src` can be used as a workaround, but it should be possible to use citation-js in the browser without compromising security.

**Comment by larsgw** [comment]
I was not aware of this, thank you for bringing it up. I will look into it.

**Comment by larsgw** [comment]
By the way, are you using the bibtex plugin? If not, you can create a bundle for the browser *without* the `moo` dependency at https://juniper-coat.glitch.me/ (or by building https://github.com/citation-js/bundle-tool yourself).

**Comment by jlaasonen** [comment]
Yes, we are using it. We need to be able to import references in BibTeX format.
