### ISSUE TITLE
`eid` (electronic identifier) output for eids not starting with "e"

### ISSUE THREAD

**Issue by AlexanderZeilmann** [citation-js/citation-js#140]
Currently ([see here](https://github.com/citation-js/citation-js/blob/1af82342ea5b216daba0aee492c6b56f57c2c999/packages/plugin-bibtex/src/mapping/biblatex.js#L457)) in the CSL to BibLaTeX conversion the `page` field is converted to `pages` and `eid` if the input starts with an `e`. If the input does not start with `e` only the `pages` field is output.

This generates a problem as I have several `eid`s that do not start with an `e`. How can I generate an `eid` output for those entries?

**Comment by larsgw** [comment]
I am unsure how to encode that when converting BibLaTeX to CSL, I think that information is lost in the process. Unless your `eid`s happen to follow a different, distinctive pattern that I could add. I could try to add an option to the formatting API to customize the process but to do that for `eid`/`page` specifically seems pretty arbitrary... What you could maybe do is manually prefix every (relevant) `page` with an `e`, convert to BibLaTeX JSON, remove the `e` from the `eid` value and remove the `pages` field entirely, but then I don't think you can easily serialize the BibLaTeX JSON with Citation.js. I will think about this later though.

**Comment by AlexanderZeilmann** [comment]
> Unless your eids happen to follow a different, distinctive pattern that I could add.

Sadly no. See for example the journals published by [IOPscience](https://iopscience.iop.org/). In most of the journals the `eid` starts with a `0` but this is not the case for all journals.

Just writing down a few thoughts:

A possibility would be to use a [custom field](https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-data.json#L444)
```json
"custom": {
    "eid": "01234"
}
```

There is also an [enhancement suggestion for CSL](https://github.com/citation-style-language/schema/issues/350) to  "add a general identifiers array variable".

**Comment by larsgw** [comment]
Maybe `number` (in combination with `volume`/`issue`), but that might be weird to map from CSL to BibLaTeX.

> A possibility would be to use a custom field

Thank you, I couldn't find the documentation when I looked for it just now. That would be a good possibility once I implement CSL 1.0.2 (which is unfortunately a breaking change).

**Comment by AlexanderZeilmann** [comment]
Same here, the only documentation for `custom` I could find is the [schema](https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-data.json#L444-L457) and the [original github issue](https://github.com/citation-style-language/schema/issues/277).

**Comment by larsgw** [comment]
I asked about it in the CSL forum: https://discourse.citationstyles.org/t/specify-article-is-electronic/1749
