### ISSUE TITLE
Investigate CSL trouble with citationsPre and citationsPost

### ISSUE THREAD

**Issue by larsgw** [citation-js/citation-js#141]
> I integrated `citation-js` as a rehype plugin - [rehype-citation](https://github.com/timlrx/rehype-citation). This was before your recent changes on master. Was not able to use `citation.js` directly and had to escape to `cite-proc` and `processCitationCluster` for that part. 
>
> For some reason `previewCitationCluster` does not interact with `citationsPre` and `citationsPost` properly - it might be to do with how it prepares and update the registry, which I am not too familiar with. Those options are needed to render footnote styles correctly since the sequence of citations matter.
>
> I still used `citation-js` for the general parsing and bibtex support so thanks for that. The CSL code was also very useful to understand how `cite-proc` works.

_Originally posted by @timlrx in https://github.com/citation-js/citation-js/issues/119#issuecomment-977721770_

**Comment by larsgw** [comment]
@timlrx I think I made a mistake with how `citationsPre` and `citationsPost` work, and I don't think I can fix it easily. For that you really need a "clean" engine to track the citations, and that's not what Citation.js expects. I think I will deprecate the options for now and implement it later, sorry.

**Comment by timlrx** [comment]
No worries, creating a clean engine to track the citations was exactly what I did. The other parts of citation.js still came in really helpful so many thanks for that.

**Comment by larsgw** [comment]
I found a solution using `CSL.Engine#rebuildProcessorState()`, it should work now.
