### ISSUE TITLE
`event` in CSL is deprecated and will be replaced by `event-title`

### ISSUE THREAD

**Issue by AlexanderZeilmann** [citation-js/citation-js#142]
Just a quick info, `event` is deprecated and will be replaced by `event-title`. See here:
https://github.com/citation-style-language/schema/blob/master/schemas/input/csl-data.json#L312

So `citation-js` should start to accept `event-title` as well.

**Comment by larsgw** [comment]
I need to update the mappings to 1.0.2 entirely but that's a breaking change (kind of) because 1.0.2 CSL data does not always work with 1.0.1 CSL styles (due to software, event-title, etc.)
