### ISSUE TITLE
invalid syntax aparsing the bibtex returned from semantic scholar

### ISSUE THREAD

**Issue by ntutangyun** [citation-js/citation-js#151]
@article{2010.01785,
	title={UNIFUZZ: A Holistic and Pragmatic Metrics-Driven Platform for Evaluating
  Fuzzers},
	author={Li, Yuwei and Ji, Shouling and Chen, Yuan and Liang, Sizhuang and Lee, Wei-Han and Chen, Yueyao and Lyu, Chenyang and Wu, Chunming and Beyah, Raheem and Cheng, Peng and Lu, Kangjie and Wang, Ting},
	year=2020,
	month=Oct,
	url=http://arxiv.org/abs/2010.01785v1,
	eprinttype = {arXiv},
	eprint=2010.01785
}

![image](https://user-images.githubusercontent.com/16061105/159215147-fcd6fdcf-bd54-467b-92bb-2cc5449b45ce.png)

**Comment by larsgw** [comment]
Thank you for this report. Those values (for url, eprint) are supposed to be in quotes or braces. How did you obtain the BibTeX from Semantic Scholar? When I clicked the Cite button I got something else:

```
@inproceedings{Li2021UNIFUZZAH,
  title={UNIFUZZ: A Holistic and Pragmatic Metrics-Driven Platform for Evaluating Fuzzers},
  author={Yuwei Li and Shouling Ji and Yuan Chen and Sizhuang Liang and Wei-Han Lee and Yueyao Chen and Chenyang Lyu and Chunming Wu and Raheem A. Beyah and Peng Cheng and Kangjie Lu and Ting Wang},
  booktitle={USENIX Security Symposium},
  year={2021}
}
```
