### ISSUE TITLE
Wikidata: Assign a more suitable entity default type than "book"

### ISSUE THREAD

**Issue by bootsa** [citation-js/citation-js#152]
The Wikidata plugin assigns a fallback value of "book" to any entities that do not have an associated type defined.

https://github.com/citation-js/citation-js/blob/0d974fa73515b9405b189c35c3e79413916f932a/packages/plugin-wikidata/src/prop.js#L196-L209

This is rather a specific identifier. A value of "text" or even, in the vain of schema.org, "thing" would be far preferable - since replacing all instances of "book" with a preferred fallback could lead to misrepresentation.

Even better would be to leave it undefined and allow a fallback value to be optionally defined in the plugin config.

**Comment by larsgw** [comment]
I agree, but CSL 1.0.1 unfortunately does not support a type like `text` or `thing`. When the upgrade to CSL 1.0.2 is made the type `document` will be available for such cases.

**Comment by larsgw** [comment]
Fixed in 09f2e2ddf47bc4bddf16022cdef37b0c40d92ee5
