### ISSUE TITLE
Abstraction over csl styles

### ISSUE THREAD

**Issue by Leon0402** [citation-js/citation-js#158]
Is there some abstraction over csl styles? Currently I can see the loaded csl with `plugins.config.get('@csl').templates`. But these are the raw xml files. 

Is there some real class for csl styles with methods to find out if the csl style is numeric for instance? 

For example https://github.com/inukshuk/csl-ruby offers a way to query these csl syles

**Comment by Leon0402** [comment]
And additionally: Does the library support https://github.com/citation-style-language/styles/tree/master? So xml files can be easily taken from there?

**Comment by larsgw** [comment]
> Is there some abstraction over csl styles? Currently I can see the loaded csl with plugins.config.get('@csl').templates. But these are the raw xml files.
>
> Is there some real class for csl styles with methods to find out if the csl style is numeric for instance?

There isn't a class but you may be able to retrieve some of that info from [`citeproc-js`](https://github.com/Juris-M/citeproc-js) (the library that Citation.js uses to handle CSL styles). If you get a (citeproc-js) CSL engine like below you can access some properties about the style, including the class (`in-text` or `note`) but unfortunately not the category (i.e. `numeric`/author-date`/etc.).

```js
const { plugins } = require('@citation-js/core')
require('@citation-js/plugin-csl')

const config = plugins.config.get('@csl')
const engine = config.engine([], 'apa', 'en-US', 'text')

console.log(engine.opt.styleName)
```

I have been working on an alternative CSL processor ([`csl-js`](https://github.com/larsgw/csl-js)) on and off for a while to see if it is feasible to replace `citeproc-js`, which does allow easier access to that info. This is not part of Citation.js though (yet).

```js
const { styles } = require('csl-js')
const styleXml = await fetch('https://cdn.jsdelivr.net/gh/citation-style-language/styles@master/apa.csl')
    .then(response => response.text())
styles.set('apa', styleXml)

const info = styles.get('apa').info
console.log(info)
// {
//   "title": "American Psychological Association 7th edition",
//   "title-short": "APA",
//   "id": "http://www.zotero.org/styles/apa",
//   "updated": "2022-01-31T14:30:00+00:00",
//   "rights": "This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 License",
//   "license": "http://creativecommons.org/licenses/by-sa/3.0/",
//   "link": {
//     "self": "http://www.zotero.org/styles/apa"
//     "template": "http://www.zotero.org/styles/apa-6th-edition"
//     "documentation": "https://apastyle.apa.org/style-grammar-guidelines/references/examples"
//   },
//   "author": [
//     {
//       "name": "Brenton M. Wiernik",
//       "email": "zotero@wiernik.org"
//     }
//   ],
//   "category": {
//     "citation-format": "author-date",
//     "field": "generic-base"
//   }
// }
console.log(info.category['citation-format'] === 'numeric')
// false
```

> And additionally: Does the library support https://github.com/citation-style-language/styles/tree/master? So xml files can be easily taken from there?

Yes, the library uses those XML files.

**Comment by Leon0402** [comment]
> There isn't a class but you may be able to retrieve some of that info from [`citeproc-js`](https://github.com/Juris-M/citeproc-js) (the library that Citation.js uses to handle CSL styles). If you get a (citeproc-js) CSL engine like below you can access some properties about the style, including the class (`in-text` or `note`) but unfortunately not the category (i.e. `numeric`/author-date`/etc.).

That's very unfortunate. I was also searching in that lib. But I didn't find good documentation for it.

> I have been working on an alternative CSL processor (csl-js) on and off for a while to see if it is feasible to replace citeproc-js, which does allow easier access to that info. This is not part of Citation.js though (yet).

Very cool! Even if it's not part of cite-js, I might still be able to use this! 

> Yes, the library uses those XML files.

I meant if the library automatically searches in the repo in any way or includes the repo. 

For instance the above mentioned library in ruby https://github.com/inukshuk/csl-ruby  allow to pass a csl name and then searches for the appropriate xml file. It defines `CSL::Style.root` which is a variable holding the search path. 
Another package https://github.com/inukshuk/csl-styles/tree/master/vendor then includes the csl repo as git submodule and sets the path to it. 

This way I'm as a user can pass just a name to the library and the library will search for the xml file under the hood. The xml files are already included from the repo, so no network request necessary. 

I probably will build something like that in my application, because fetching from some urls is not possible. The stiles need to be local. But it would be more convenient if citation-js already had something like this obviously :)

**Comment by larsgw** [comment]
> I meant if the library automatically searches in the repo in any way or includes the repo.

Ah, I see. No, that is not supported yet, but it has been suggested before (https://github.com/citation-js/citation-js/issues/92) and I might implement it at some point.
