### ISSUE TITLE
Using lang to specify locale not working?

### ISSUE THREAD

**Issue by gabestein** [citation-js/citation-js#166]
## What version of Citation.js are you using?
0.6.2

## How are you running Citation.js (npm package, browser bundle, self-rolled bundle, webpack)?
npm package with webpack

## Where are you running Citation.js? * The OS usually will not matter much, but the browser really does.
PubPub / Chrome latest

## What is your input data and code?
Input Data:
```
{
  type: 'article-journal',
  title: 'Hmm ok\n',
  author: [Array],
  editor: [Array],
  'container-title': 'Journal of KFG',
  containerDoi: '10.21428/0417b0c0.2ef9383d',
  ISBN: undefined,
  ISSN: null,
  edition: undefined,
  volume: '',
  issue: '',
  publisher: '',
  DOI: '10.21428/0417b0c0.2ef9383d',
  issued: [Array],
  note: 'http://localhost:9876/pub/d9511nz9',
  URL: 'http://localhost:9876/pub/d9511nz9',
}
```
```Cite.format('bibliography', { format: 'html', template: 'harvard', lang: 'en-US' });```

## What did you expect to happen, and what actually happened?
Expected:

`Dent, A. et al. (2022) 'Hmm ok', Journal of KFG [Preprint]. Edited by I. Reynolds. doi:10.21428/0417b0c0.2ef9383d.`

Got:

`Dent, A. et al. (2022) "Hmm ok," Journal of KFG [Preprint]. Edited by I. Reynolds. doi:10.21428/0417b0c0.2ef9383d.`

I also did the same passing `fr` into an APA style with an editor, and did not see any of the French editor terms `éd.` with the accent vs. `ed.`

When I manually downloaded the harvard-cite-them-right csl and changed the default locale to en-US, the citation appeared as expected.

This appears to be a known-ish thing (https://github.com/citation-style-language/styles/issues/5956), but Zotero, which also uses citproc-js, doesn't have the issue, and manually changing the locale in the CSL file works, so my guess is this comes down to citation-js's locale handling.

**Comment by larsgw** [comment]
Oh I see, it is a bug in Citation.js. It passes a language by default but that overrides the `default-locale`.

**Comment by larsgw** [comment]
Fix released in `0.6.3`

**Comment by gabestein** [comment]
Confirm it works well, but there's one potential wrinkle that I'm not sure is intended that I wanted to give you a heads up on. Now, when you don't specify a language for Harvard, it throws the error `citeproc-js error: unable to parse XML input`. May be due to Harvard having a default locale set? Does not happen with APA.

## Input
```
{
  type: 'article-journal',
  title: 'Hmm ok\n',
  author: [Array],
  editor: [Array],
  'container-title': 'Journal of KFG',
  containerDoi: '10.21428/0417b0c0.2ef9383d',
  ISBN: undefined,
  ISSN: null,
  edition: undefined,
  volume: '',
  issue: '',
  publisher: '',
  DOI: '10.21428/0417b0c0.2ef9383d',
  issued: [Array],
  note: 'http://localhost:9876/pub/d9511nz9',
  URL: 'http://localhost:9876/pub/d9511nz9',
}
```

```Cite.format('bibliography', { format: 'html', template: 'harvard' });```

**Comment by larsgw** [comment]
Yeah normally unavailable locales are handled but in this case Citation.js does not know about the locale so it cannot handle it directly. For compatibility I made it fail silently in 974ea05bd65f7f0753e83d0544d47a818ed3e935. This makes it harder to debug of course but that is the trade-off until the next major version.
