### ISSUE TITLE
Output format "bibliography" unavailable; The register seems to only have 'data' in it when I debug

### ISSUE THREAD

**Issue by cclpeng** [citation-js/citation-js#179]
I am new to using citation-js, and I want to use it in my javascript application. I installed it with the command from the npm page: "npm install @citation-js/core". 

I get this error when I try to do 
`     
      const jdata = {
      type: docInfo[DTYPE], etc. };

      let example = new Cite(jdata);
      let output = example.format('bibliography', {
        format: 'html',
        template: 'apa',
        lang: 'en-US'
      })`

`Uncaught (in promise) Error: Output format "bibliography" unavailable

    at format (output.js:27:1)
    
    at Cite.format (get.js:8:20)
    
    at _callee12$ (taskpane.js:442:28)
    
    at tryCatch (runtime.js:63:16)
    
    at Generator.invoke [as _invoke] (runtime.js:293:1)
    
    at Generator.next (runtime.js:118:1)
    
    at asyncGeneratorStep (CitationFormatterService.js:468:1)
    
    at _next (CitationFormatterService.js:468:1)
    
    at CitationFormatterService.js:468:1
    
    at new Promise (<anonymous>)`
    
* "CitationFormatterService" is just my file that I tried to use citation-js in. 

The output.js file is this one: packages\core\src\plugins\output.js
When I go to that "format" function, it seems the issue is the register object doesn't have 'bibliography' inside. In the console, I tried to print out what the register object looked like, so I've attached a screenshot upload of it. It seems like the register object only has 'data' inside, so it doesn't have 'bibliography'. 

Does anyone know if I just made a mistake somewhere along the way, or is there an issue with how the register object should be populated with the other values?
![image](https://user-images.githubusercontent.com/17967931/192608859-6bcd6313-b9ae-4848-b4b7-325f928a982c.png)

**Comment by larsgw** [comment]
The different output formats are in plugins. You can install the plugin for `bibliography` with `npm install @citation-js/plugin-csl` and load it with `require('@citation-js/plugin-csl')`. If you have any questions let me know.

**Comment by cclpeng** [comment]
Wow thanks so much for the fast response! It helped me resolve this issue. Thank you for helping me with my noob question

**Comment by larsgw** [comment]
No problem, happy to help!
