### ISSUE TITLE
Additional Wikidata property mappings

### ISSUE THREAD

**Issue by larsgw** [citation-js/citation-js#18]
### Add

  * [`P407` (language of work or name)](https://www.wikidata.org/wiki/Property:P407): `language`*
  * [`P921` (main subject)](https://www.wikidata.org/wiki/Property:P921): `keyword`* as per Zotero (previously ignored)
  * [`P1752` (scale)](https://www.wikidata.org/wiki/Property:P1752): `scale`
  * [`P437` (medium)](https://www.wikidata.org/wiki/Property:P437): `medium`*
  * [`P1817` (addressee)](https://www.wikidata.org/wiki/Property:P1817): `recipient`*
  * (none): `source` could be `'Wikidata'`

_* requires fetching additional resources_

### Ignore

  * [`P5875` (ResearchGate publication ID)](https://www.wikidata.org/wiki/Property:P5875)
  * [`P2284` (price)](https://www.wikidata.org/wiki/Property:P2284)
  * [`P648` (Open Library ID)](https://www.wikidata.org/wiki/Property:P648)
  * [`P2507` (corrigendum / erratum)](https://www.wikidata.org/wiki/Property:P2507) unfortunately
  * [`P5008` (on focus list of Wikimedia project)](https://www.wikidata.org/wiki/Property:P5008)

### Undecided

  * [`P856` (official website)](https://www.wikidata.org/wiki/Property:P856): `URL`?

**Comment by larsgw** [comment]
See also https://github.com/larsgw/citation.js/issues/76

**Comment by davidar** [comment]
I think mapping P856 to URL when P953 is missing would be useful.

**Comment by larsgw** [comment]
### Change

  * [`P291` (place of publication)](https://www.wikidata.org/wiki/Property:P291) to [`P123` (publisher)](https://www.wikidata.org/wiki/Property:P123) + [`P740` (location of formation)](https://www.wikidata.org/wiki/Property:P740)

### Remove

  * [`P136` (genre)](https://www.wikidata.org/wiki/Property:P136) and `medium` mentioned above, due to the discussion regarding those two variables

**Comment by larsgw** [comment]
### Add

  * [`P629` (edition or translation of)](https://www.wikidata.org/wiki/Property:P629): `original-*`
  * [`P921` (main subject)](https://www.wikidata.org/wiki/Property:P921): `reviewed-*` if type is `review`/`review-book`
  * [`P361` (part of)](https://www.wikidata.org/wiki/Property:P361): `container-*` if type is `chapter` (or `inproceedings`?)
  * [`P179` (part of the series)](https://www.wikidata.org/wiki/Property:P179): `collection-*` (apart from `collection-number`, which should be the qualifier [`P1545` (series ordinal)](https://www.wikidata.org/wiki/Property:P1545))
  * [`P1433` (published in)](https://www.wikidata.org/wiki/Property:P1433) + [`P4745` (is proceedings from)](https://www.wikidata.org/wiki/Property:P4745): `event-*`

Note the changes from the original intentions with `original-title`.

**Comment by larsgw** [comment]
### More

  * [`P1160` (ISO 4 abbreviation)](https://www.wikidata.org/wiki/Property:P1160): `journalAbbreviation`/`container-title-short`
