### ISSUE TITLE
DOI regular expression fails on some cases

### ISSUE THREAD

**Issue by Reddine** [citation-js/citation-js#182]
- What version of Citation.js are you using?
_@citation-js/core_ **0.6.1**, _@citation-js/plugin-doi_ **0.6.1**
- How are you running Citation.js (npm package, browser bundle, self-rolled bundle, webpack)?
npm package
- Where are you running Citation.js? * The OS usually will not matter much, but the browser really does.
Firefox 105.0.3
- What is your input data and code?
**Input**: 10.1002/1520-6394(2000)12:3<118::AID-DA2>3.0.CO;2-G
**code**: Cite.async("10.1002/1520-6394(2000)12:3<118::AID-DA2>3.0.CO;2-G")
- What did you expect to happen, and what actually happened?
It should get the metadata but it gives `This format is not supported or recognized`

I checked the code and it seems the package uses an [outdated regular expression](https://github.com/citation-js/citation-js/blob/main/packages/plugin-doi/src/index.js#L84) recommended by Crossref.

The input is a valid doi as you can see here: https://pubmed.ncbi.nlm.nih.gov/11126185/

and it's resolvable by Crossref API: https://api.crossref.org/works/10.1002%2F1520-6394(2000)12%3A3%3C118%3A%3AAID-DA2%3E3.0.CO%3B2-G

A possible solution would be to update the regular expression as [this comment](https://stackoverflow.com/questions/27910/finding-a-doi-in-a-document-or-page/10300246#comment24134610_10324802) suggest:

```
\b(10[.][0-9]{4,}(?:[.][0-9]+)*/(?:(?!["&\'])\S)+)\b
```

**Comment by larsgw** [comment]
Thank you for the report. Unfortunately changing the pattern is a (small) breaking change as other plugins may have similar formats and the new overlap would break the second-loaded plugin. I don't think this matters in practice though, and I am not aware of published third-party plugins. While I mull this over, you can work-around by locally updating the type parser:

```js
const { plugins } = require('@citation-js/core')

plugins.input.add("@doi/api", {
  parseType: {
    dataType: 'String',
    predicate: /\b(https?:\/\/(?:dx\.)?doi\.org\/(10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'])\S)+))\b/i,
    extends: '@else/url'
  }
})

plugins.input.add("@doi/id", {
  parseType: {
    dataType: 'String',
    predicate: /\b(10[.][0-9]{4,}(?:[.][0-9]+)*\/(?:(?!["&\'])\S)+)\b/
  }
})
```

([Try it online](https://runkit.com/larsgw/citation-js-doi-pattern-replacement/1.0.1))

**Comment by Reddine** [comment]
Thanks for the snippet and your efforts!

**Comment by mfenner** [comment]
The DOI is a [SICI](https://en.wikipedia.org/wiki/Serial_Item_and_Contribution_Identifier). They were used mainly in the early years of Crossref and are difficult to handle, as the contain characters that break URLs unless escaped.

There is no regex that detects all valid DOIs, just the majority of them. There are very few hard rules, e.g. about the prefix, or that DOIs are case insensitive.
