### ISSUE TITLE
Is there a way to add a custom Page/Chapter/Folio/Column/etc. to the "citation" format type , if the data is only a DOI?

### ISSUE THREAD

**Issue by cclpeng** [citation-js/citation-js#183]
I'm still new to using citation-js, and so far I like how I can provide just the DOI to the Cite constructor, and it can generate the inline citations, and bibliography. 

However, I am using the MLA format, too, and MLA's inline citation often adds the page/chapter, column, section, etc. number that the quote or paraphrased part comes from. I am hoping there's already a way to provide this, and I'm just not finding it. 

For example, if I have this 
```
let example = new Cite('10.5281/zenodo.1005176')
example.format('citation', {
      format: 'html',
      template: template, // <- this one is the mla template I added
      lang: 'en-US'
    });
```

Is there a way I can keep the data as only the DOI, and also give it something like "page 2" so that my inline citation can be something like 

"  (Smith 2) "
instead of what it currently is 
"  (Smith) "?

**Comment by larsgw** [comment]
Thank you for opening an issue. The code snippet is not entirely correct, templates have to be added in a different way:

```js
const { Cite, plugins } = require('@citation-js/core')

const cslConfig = plugins.config.get('@csl')
cslConfig.templates.add('mla', template) // <- this one is the mla template I added

let example = new Cite('10.5281/zenodo.1005176')
example.format('citation', {
      format: 'html',
      template: 'mla',
      lang: 'en-US'
    });
```

**Comment by cclpeng** [comment]
Oh sorry, I didn't remember to show you some parts. I think I did something similar to what you had. 

I have an import like this below, and it's a file called mla.js that has some xml for the mla template I found online on github: https://github.com/seulibrary/Sorin/blob/fd43a46afb1259635d59486291157235bae8fe56/apps/frontend/assets/js/components/Citation/plugins/mla.js
import mla from '../citation-templates/mla';

Then I did 
Cite.CSL.register.addTemplate("mla", mla); 
so when I did 

example.format('citation', {
      format: 'html',
      template: template, // <- this one is the mla template I added
      lang: 'en-US'
    });
    
    the "template" variable is actually just a string "mla" or "apa" that I want to support for my app. 
    
    
    
    I saw the Cite instance "example" has example.data[0], and after creating it with only: new Cite("<doi>"), citation-js was able to populate fields like author, publisher, volume. I tried to add to this, by doing 
    
    example.data[0].page = "200-300", but even though I made the template "mla", it didn't apply a page number to the "citation" type 
    
    
    
    I did try exactly what you gave me though, and replaced "Cite.CSL.register.addTemplate("mla", mla); ", but I think I still am not able to get the mla format of (Smith 2) instead of (Smith)

**Comment by cclpeng** [comment]
Oh I believe I found the solution now while I was reading your README for your plugin-csl, and the file with examples: citation-js\packages\plugin-csl\src\citation.js

It looks like if I want to put some part numbers, I should follow a format like this: 
`citeObj.format('citation', {
      format: 'html',
      template: 'mla',
      lang: 'en-US',
      entry: [{ id:'temp_id_6623842166019887',  label: 'page', locator: 123 }, 
              { id: citeObj.data[1].id, label: "folio", locator: 22}, 
              { id: citeObj.data[2].id, label: 'sub verbo', locator: 8}]
    });
    to get something like this:
'(Boada et al. 123; Boada et al., fol.22; Moretti, s.v.8)'`

and it turns out it would work the same for other templates, like when I switch the template to "apa", the result is 
'(Boada et al., 2020, p. 123, 2020, fol. 22; Moretti, n.d., s.v. 8)'


Hopefully it's all solved for me now, so thank you for your work! I'll ask again if I have more trouble.
