### ISSUE TITLE
adding pages to citation

### ISSUE THREAD

**Issue by dwhieb** [citation-js/citation-js#184]
In the citation style used in my field (linguistics; see the [CSL template here](https://github.com/citation-style-language/styles/blob/master/generic-style-rules-for-linguistics.csl)), page numbers should be included with citations whenever appropriate, e.g.

> Other researchers have documented this fact as well (Hieber 2019: 53).

How can I format citations to include page numbers?

I'm currently using `cite.format('citation')` with the template mentioned above, and it formats correctly, but I don't know how to add the page number to the citation.

Thanks!

**Comment by dwhieb** [comment]
Between the discussion in #119 and citeproc's [documentation on cite-items](https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cite-items), I pieced together the following, which works exactly as expected:

```js
const output = cite.format(`citation`, {
  entry: {
    id:      `Hieber2019`,
    locator: 53,
  },
  template: `ling`,
})

console.log(output) // "(Hieber 2019: 53)"
```

You might want to update the documentation for the `entry` option to mention that it also accepts cite-item objects in addition to strings (see [here](https://citation.js.org/api/0.3/module-output_csl.html#~citation) in the docs).

Very happy this functionality was possible though! Thanks!

**Comment by dwhieb** [comment]
Oh interesting! That would've helped haha. I obviously didn't catch that. It looks like the _Documentation_ link beneath the citation.js logo on [this page](https://citation.js.org/api/0.5/) takes me to v0.3 instead of the latest version.

The example in the more updated documentation would have been all I needed, so I think it's fine as is.

**Comment by larsgw** [comment]
Ah I see. I decided to redirect to the old version by default to not break URLs from before I included the version number in the URL, but that's confusing.
