### ISSUE TITLE
Allow custom RIS translations

### ISSUE THREAD

**Issue by UcDust** [citation-js/citation-js#185]
What's the best method to override the RIS tag translations? Can we plug in other translation.json files, or would we need to fork?

Specifically for the `paper-conference` type, the citation-js module translates the `issued` component into a `C2` entry in RIS. We need to use the RIS in another system, but it doesn't support that custom tag, and instead only supports the traditional `DA` tag for conf dates.

**Comment by larsgw** [comment]
Right now this is not configurable, and would need a full fork (of the RIS plugin, not necessarily Citation.js in its entirety). There's a good case to fix this in a different way though: the mapping `DA` → `issued` is already included, but `C2` is prefered, and in the reverse case only the most prefered field is outputted. It might make sense to (optionally or by default) output all fields, if there is no conflict.

**Comment by UcDust** [comment]
Nice! We were considering that option actually, that would definitely work for us, and save some pain.

**Comment by larsgw** [comment]
RIS is a very annoying format in that every implementation has slightly different specifications, to a greater degree than even BibTeX. The specifications are a bit inaccessible to be fair, but still. Also there's two pretty different versions of the format, with most implementations using features from both :)

I don't think I have time to think about this this weekend, but I will see when I have time. If you do end up making a fork in the meantime, I think would be as simple as changing the order of this array:

https://github.com/citation-js/citation-js/blob/5f5fde5e2b0962d649192074d47ec435c0a7ec63/packages/plugin-ris/src/spec/new.json#L678-L681

**Comment by larsgw** [comment]
Actually now that I look at it in more detail, this may have been a bug in the mapping generator for several reasons. Sorry, that is an entirely different case. I will take a look.
