### ISSUE TITLE
Case-sensitive Name and List Separators in BibTeX Plugin

### ISSUE THREAD

**Issue by ech0-de** [citation-js/citation-js#188]
The name list separator and list separator of plugin-bibtex seem to be case sensitive (see [packages/plugin-bibtex/src/input/value.js#L35](https://github.com/citation-js/citation-js/blob/main/packages/plugin-bibtex/src/input/value.js#L35)) whereas the implementation used by bibtex and biber is [case insensitive](https://manpages.debian.org/testing/libbtparse-dev/bt_split_names.3.en.html#bt_split_list()). This leads to names being incorrectly parsed when separated by an uppercase AND as shown in the example code below.

This behavior may be intended, as the biblatex spec is a bit vague on this matter, but it might be better to share the behavior of biber and bibtex. To fix this behavior it might be as simple as changing adding the `i` modifier to the `and` regex, but I haven't tested this.

> 1. What version of Citation.js are you using?
>   @citation-js/core@0.6.5 and @citation-js/plugin-bibtex@0.6.5
> 1. How are you running Citation.js (npm package, browser bundle, self-rolled bundle, webpack)?
>   npm package
> 1. Where are you running Citation.js? * The OS usually will not matter much, but the browser really does.
>   node v19.4.0
> 1. What is your input data and code?
> ```js
> const { Cite, plugins } = require('@citation-js/core');
> require('@citation-js/plugin-bibtex');
> 
> const bibtex = `
> @inproceedings{10.1145/1499402.1499562,
> author = {Lesk, M. E. AND Kernighan, B. W.},
> title = {Computer Typesetting of Technical Journals on UNIX},
> year = {1977},
> isbn = {9781450379144},
> publisher = {Association for Computing Machinery},
> address = {New York, NY, USA},
> url = {https://doi.org/10.1145/1499402.1499562},
> doi = {10.1145/1499402.1499562},
> booktitle = {Proceedings of the June 13-16, 1977, National Computer Conference},
> pages = {879–888},
> numpages = {10},
> location = {Dallas, Texas},
> series = {AFIPS '77}
> }`;
> 
> const citation = new Cite(bibtex);
> console.log(citation.data[0].author);
> ```
> 5. What did you expect to happen, and what actually happened?
>  expected output:
> ```js
> [
>   { given: 'M. E.', family: 'Lesk' },
>   { given: 'B. W.', family: 'Kernighan' }
> ]
> ```
> 
> actual output:
> ```js
> [ { given: 'B. W.', family: 'Lesk', suffix: 'M. E. AND Kernighan' } ]
> ```

**Comment by larsgw** [comment]
I think it's slightly more difficult because moo, the lexer library, probably can't handle that.
