### ISSUE TITLE
Cannot use plugins with require in Next.js application

### ISSUE THREAD

**Issue by unidesigner** [citation-js/citation-js#194]
I ran into the issue that the plugins I added in my Next.js react application (i.e. with server side rendering) are not properly registered with
```
const { Cite } = require('@citation-js/core')
require('@citation-js/plugin-csl')
```
I do get a `Uncaught (in promise) TypeError: n is undefined` when I call
```
let data = new Cite(...)
let reference = data.format('citation')
```
I think the issue is that the import of the plugins does not have any exports that I could use to register them myself, something like
```
const { Cite, plugins } = require('@citation-js/core')
const { pluginconfig } = require('@citation-js/plugin-csl')
plugins.add('@csl', pluginconfig)
```
Any help or suggestion would be greatly appreciated!

**Comment by larsgw** [comment]
An API like that would be beneficial (and has been suggested in #30) and may cause this problem, but the error also indicates there is something else going wrong. If the plugin was not registered in the first place you would presumably get the same error, which is not good behavior. If you have example code (or an example repository) to reproduce the error I can check it out.

**Comment by unidesigner** [comment]
Hi @larsgw , thanks for getting back to me. I think the reason for the issue is exactly what is described in #30. It would be required to move code from ES5 to ES6 (or at least add an appropriate module export), which would then enable a manual registration of plugins that were imported.

To reproduce the error, I have setup a basic next.js repo [here](https://github.com/unidesigner/citation-js-test).

You can do
```
npm install
npm run dev
```
And then click on the test button. You should see this:
![Screenshot from 2023-04-22 18-03-51](https://user-images.githubusercontent.com/136799/233795102-df070dae-196f-446d-8b48-c850d5494f35.png)

When you build the site and serve it with
```
npm run build
npm run start
```
You get the error:
![Screenshot from 2023-04-22 18-03-36](https://user-images.githubusercontent.com/136799/233795126-c2b5d2f1-99ba-4980-ad93-3217d0fe7422.png)

I was spending some time looking into potential alternatives for citeproc-js for react, but I did not find anything that worked and is maintained. I really think citation-js is one of the best and most flexible packages available, and it would be great to be able to use it for modern server-side rendered applications. Let me know if I can help in some way.

Probably all the plugin packages have to be updated for this. I was thinking if it may make sense to create a new package for react-specifically which bundles all the dependencies, and exposes some usable react components, similar to [this unmaintained package](https://github.com/robindemourat/react-citeproc/).

**Comment by larsgw** [comment]
I'll take a look at the repo, thank you. I just want to note that citation-js also uses citeproc-js for the csl plugin.

**Comment by larsgw** [comment]
I don't think the repo has all the commits yet.

**Comment by unidesigner** [comment]
Oups, I added the commit.

**Comment by larsgw** [comment]
I've been looking at the stacktrace and the generated code, and it doesn't make sense to me at all to me. This is the original code in `citeproc-js`:

```js
    // Build skip-word regexp
    function makeRegExp(lst) {
        var lst = lst.slice();
        var ret = new RegExp( "(?:(?:[?!:]*\\s+|-|^)(?:" + lst.join("|") + ")(?=[!?:]*\\s+|-|$))", "g");
        return ret;
    }
    this.locale[this.opt.lang].opts["skip-words-regexp"] = makeRegExp(this.locale[this.opt.lang].opts["skip-words"]);
```

And this is what I see in the generated file:

```js
this.locale[this.opt.lang].opts["skip-words-regexp"]=(this.locale[this.opt.lang].opts["skip-words"],RegExp("(?:(?:[?!:]*\\s+|-|^)(?:"+(n=n.slice()).join("|")+")(?=[!?:]*\\s+|-|$))","g"))
```

or re-formatted:

```js
this.locale[this.opt.lang].opts["skip-words-regexp"] = (
  this.locale[this.opt.lang].opts["skip-words"],
  RegExp("(?:(?:[?!:]*\\s+|-|^)(?:" + (n = n.slice()).join("|") + ")(?=[!?:]*\\s+|-|$))", "g")
)
```

And `n` is never defined in this code (only as `var n` and I'm not sure whether that relates or not). So I think this might have more to do with the optimization of the code than the dependencies.

**Comment by larsgw** [comment]
In fact, just that snippet reproduces it:

```jsx
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
    function foo () {
        function makeRegExp(lst) {
            var lst = lst.slice();
            var ret = new RegExp( "(?:(?:[?!:]*\\s+|-|^)(?:" + lst.join("|") + ")(?=[!?:]*\\s+|-|$))", "g");
            return ret;
        }
        this.locale[this.opt.lang].opts["skip-words-regexp"] = makeRegExp(this.locale[this.opt.lang].opts["skip-words"]);
    }

    const test = async () => {
        foo.call({ locale: { en: { opts: {} } }, opt: { lang: 'en' } })
    }

    return (
        <>
            <div>
                <button onClick={test}>Test</button>
            </div>
        </>
    )
}
```

**Comment by larsgw** [comment]
```js
function function_name (arg_name) {
    var arg_name = arg_name.slice()
    return arg_name.join('-')
}
console.log(function_name(['ab', 'bc', 'ca']))
```

**Comment by larsgw** [comment]
I've opened https://github.com/vercel/next.js/issues/48731

**Comment by larsgw** [comment]
I'll close for now, I don't control `citeproc-js` (not enough to patch this quickly at least, but I've opened a ticket there too: https://github.com/Juris-M/citeproc-js/issues/223). Feel free to re-open if you encounter other issues after next.js/webpack/etc. is fixed.

**Comment by unidesigner** [comment]
Thank you for investigating this issue and posting upstream! I hope someone will be able reply to get it fixed.
