### ISSUE TITLE
CSL plugin seems to ignore sort order

### ISSUE THREAD

**Issue by crystalfp** [citation-js/citation-js#195]
Thanks for the library! Solved (almost) the problem of selecting, sorting and formatting a bibliography,
The problem I have is that the formatted output is not sorted but retains the order in the bib file. But, if I select a subset of entries, they are magically correctly ordered (see comment in the code).
The code for the sorting by year reverse function (note traces of typing for Typescript):
```
const sortingByYear = (first: CitationData, second: CitationData): number => {
	const dateF = first.issued["date-parts"][0];
	const dateS = second.issued["date-parts"][0];

	const deltaYears = Number.parseInt(dateS[0], 10) - Number.parseInt(dateF[0], 10);
	if(deltaYears !== 0) return deltaYears;
	const deltaMonths = Number.parseInt(dateS[1] ?? "1", 10) - Number.parseInt(dateF[1] ?? "1", 10);
	if(deltaMonths !== 0) return deltaMonths;
	return Number.parseInt(dateS[2] ?? "1", 10) - Number.parseInt(dateF[2] ?? "1", 10);
};
```
Here the code that creates the bibliography (my CSL file will be added later):
```
	const csl = (plugins as CitationPlugins).config.get("@csl");
	const cite = new Cite(bibFileBody) as CitationClass;

	cite.sort(sortingByYear);
	const sortedData = cite.data;

	const ids: string[] = [];
	for(const entry of sortedData) {
		console.error(entry.issued); // <-- this shows the entries correctly ordered
               // if(entry keyword !== "poster") continue; // <-- if I uncomment this line, the output is sorted
		ids.push(entry.id);
	}

	const citeproc = csl.engine(sortedData, "apa", "en-US", "html");
	citeproc.updateItems(ids);
	const formattedBibliography = citeproc.makeBibliography();

	for(const line of formattedBibliography[1]) {
		console.error(line); // <-- This show lines in original order (unless using a subset of ids)
	}
```
Thanks for your help!
mario

**Comment by larsgw** [comment]
By default the CSL plugin uses the sorting defined in the style (here `"apa"`). Right now you're basically using the [`citeproc`](https://github.com/Juris-M/citeproc-js) dependency directly in which case you can pass `true` as the second argument to `updateItems` to keep your sort order.

**Comment by crystalfp** [comment]
Oh, I forgot that these functions are from citeproc! Now it works correctly. Thanks!
