### ISSUE TITLE
Mapping field name to another one

### ISSUE THREAD

**Issue by crystalfp** [citation-js/citation-js#197]
I have a bibliography in which the entry language is in the `langid` field and not `language` (I think this was required by the biblatex package). I tried:
```
import {plugins, Cite} from "@citation-js/core";
import "@citation-js/plugin-bibtex";

const config = plugins.config.get("@bibtex");
config .parse.strict = false;
config.types.bibtex.source.langid = "language";
config.types.biblatex.source.langid = "language";
```
But this does nothing (and the documentation is not super-clear).
Is this the intended usage of this plugin mapping?
Thanks!
mario

**Comment by larsgw** [comment]
`config.types` is used for mapping the entry types, not the fields. The field mappings are currently not extendable. However `langid` should be mapped by default (at least for BibLaTeX input). Setting `langid` in BibLaTeX output is more difficult as it would have to validate that the value is in the `babel` or `polyglossia` packages.

**Comment by crystalfp** [comment]
Thanks @larsgw for the clarification! Anyway, seems the `langid` field is not mapped. With the following entry:
```
@Book{Valle2023,
  author    = {Mario Valle and Antonella Galgano},
  publisher = {Corriere della Sera},
  title     = {La libertà},
  year      = {2023},
  month     = mar,
  series    = {Percorsi Montessori},
  volume    = {19},
  issn      = {2532-64314},
  keywords  = {montessori},
  langid    = {italian},
}
```
Read by this code:
```
import {plugins, Cite} from "@citation-js/core";
import "@citation-js/plugin-bibtex";

const config = plugins.config.get("@bibtex");
config.parse.strict = false;
config.parse.sentenceCase = "never";
config.parse.biblatex = true;

const cite = new Cite(bibFilesContent, {generateGraph: false});
console.log(JSON.stringify(cite.data, undefined, 2))
```
Produces this output:
```
[
  {
    "author": [
      {
        "given": "Mario",
        "family": "Valle"
      },
      {
        "given": "Antonella",
        "family": "Galgano"
      }
    ],
    "collection-title": "Percorsi Montessori",
    "type": "book",
    "id": "Valle2023",
    "citation-key": "Valle2023",
    "ISSN": "2532-64314",
    "issued": {
      "date-parts": [
        [
          2023,
          3
        ]
      ]
    },
    "keyword": "montessori",
    "publisher": "Corriere della Sera",
    "title": "La libertà",
    "volume": "19"
  }
]
```
You see, the `langid` field disappeared.

Yes, a quick&dirty solution is to `.replaceAll("langid", "language")` after reading the bib file. But I want to understand the library to use it better.

Thanks for your help!
mario

**Comment by larsgw** [comment]
Yes, I meant that it *should* be mapped in the future, at least for reading input. It isn't at the moment as you point out.
