### ISSUE TITLE
Include DOI in exported BibTeX?

### ISSUE THREAD

**Issue by jheer** [citation-js/citation-js#204]
It looks like DOIs are not passed through to BibTeX output.

This snippet:

```js
const Cite = require('citation-js');
const cite = new Cite('10.5281/zenodo.1005176');
cite.format('bibtex')
```

produces the following:

```
@misc{Willighagen2018larsgw,
	author = {Willighagen, Lars and Willighagen, Egon and Badger, The Gitter and {\v C}erm{\' a}k, Petr and Wienke, Johannes},
	year = {2018},
	month = {nov 2},
	publisher = {Zenodo},
	title = {larsgw/citation.js: v0.4.0-10},
}
```

No DOI is included, even though `cite.data[0].DOI` is `10.5281/ZENODO.1005176`. This also stands in contrast to the (outdated?) example here: https://larsgw.github.io/citation.js/api/tutorial-cite_output.html

Apologies if I'm overlooking anything here. Is there a reason DOIs are not included? Is there an opt-in way to include them? FWIW some publishers now require that papers include linked DOIs in bibliographies, generated from BibTeX `doi` attributes.

**Comment by larsgw** [comment]
The BibTeX output is now strict. You could export BibLaTeX but that also depends on your requirements. I'm away now, but I can take a look at alternative solutions later.

**Comment by kc9jud** [comment]
@larsgw Just stumbled across this... isn't that a `.bst`-dependent statement? For instance, `revtex.bst` absolutely supports `doi` as a tag. There is a standard set of tags, but BibTeX does not claim that non-standard tags are forbidden:

> There is a set of standard-tags existing, which can be interpreted by BibTeX or third-party tools. Those which are unknown are ignored by BibTeX, thus can be used to store additional information without interfering with the final outcome of a document.

https://www.bibtex.org/Format/

Do beware, most journals (at least in physics) do not support BibLaTeX, so that is not a realistic replacement for BibTeX at this point.

**Comment by larsgw** [comment]
> Just stumbled across this... isn't that a `.bst`-dependent statement? For instance, `revtex.bst` absolutely supports `doi` as a tag. There is a standard set of tags, but BibTeX does not claim that non-standard tags are forbidden:
>
> > There is a set of standard-tags existing, which can be interpreted by BibTeX or third-party tools. Those which are unknown are ignored by BibTeX, thus can be used to store additional information without interfering with the final outcome of a document.
>
> https://www.bibtex.org/Format/


That's a fair point. I guess there's still not an authoritative list of tags but I can add them as requests come in. I'll need to double-check that built-in `.bst` files do not give warnings for such tags.

> Do beware, most journals (at least in physics) do not support BibLaTeX, so that is not a realistic replacement for BibTeX at this point. (Yes, those journals need `year` rather than `date`...)

Yes, that would really depend on the user.

**Comment by kc9jud** [comment]
I think the closest you'll get to an authoritative list is from the BibTeX manual: http://mirrors.ctan.org/biblio/bibtex/base/btxdoc.pdf

**Comment by larsgw** [comment]
That's what I've taken as a guideline in this implementation, but it doesn't include `doi` or `url` so I'll have to add those as requests come in. But the output cannot account for every `.bst` file of course.

**Comment by larsgw** [comment]
Okay, just to confirm older `.bst` files do not seem to complain for "unknown" fields. In terms of authoritative lists, I did find that `natbib` has "newer" styles in the `plainnat` family, which introduces some new fields: `doi`, `isbn`, `issn`, `eid`, and `url`. I'm adding those now.
