### ISSUE TITLE
Module not found: Error: Can't resolve '@citation-js/plugin-bibtex/lib/mapping/bibtexTypes' in '/node_modules/citation-js'

### ISSUE THREAD

**Issue by lightninglu10** [citation-js/citation-js#206]
Hey all, I've installed `citation-js` in my project with `yarn install citation-js` but am unable to import it. Getting an error here that a file in @citation-js/plugin-bibtex does not exist so my modules won't import. Any way to get around this?

**Comment by larsgw** [comment]
This is caused by the file extensions missing from the require statements in https://github.com/larsgw/citation.js/blob/main/index.js.

**Comment by larsgw** [comment]
(Without file extensions works on some platforms but not on all)

**Comment by lightninglu10** [comment]
Yeah I think I noticed that issue trying to debug it locally -- should I create a PR for it?

**Comment by larsgw** [comment]
I have a patch already, it's just that the release of `citation-js` is linked to `@citation-js/core` and so I cannot easily release a new version of the former without the latter.
