### ISSUE TITLE
Container-title isn't properly abbreviated (short) in Bibliography when using IEEE as the CSL template, for article-journal type

### ISSUE THREAD

**Issue by cclpeng** [citation-js/citation-js#207]
According to this section of the IEEE CSL template regarding the bibliography, article-journal types should have the container-title italicized and short.
```
        <!-- Specific Formats -->
        <if type="article-journal">
          <group delimiter=", ">
            <text macro="title"/>
            <text variable="container-title" font-style="italic" form="short"/>
            <text macro="locators"/>
            <text macro="page"/>
            <text macro="issued"/>
            <text macro="status"/>
          </group>
```
I found this CSL template for IEEE from zotero: https://www.zotero.org/styles/ieee  <-- That link downloads the .csl file for me, 
and I searched for the Bibliography section
  
  <bibliography entry-spacing="0" second-field-align="flush">

My example bibliography output is this however:
D. G. Tenen, L. Chai, and J. L. Tan, “Metabolic alterations and vulnerabilities in hepatocellular carcinoma,” _Gastroenterology Report_, vol. 9, no. 1, pp. 1–13, Nov. 2020, doi: 10.1093/gastro/goaa066.

The container-title "Gastroenterology Report" is italicized, but it's not abbreviated.

For the example, here is the CiteObject to json (with some of the irrelevant fields not included):
Wanted to highlight the type is "article-journal", and the container-title is "Gastroenterology Report."
```
{
  "publisher": "Oxford University Press (OUP)",
  "issue": "1",
  "DOI": "10.1093/gastro/goaa066",
  "type": "article-journal",
  "page": "1-13",
  "title": "Metabolic alterations and vulnerabilities in hepatocellular carcinoma",
  "prefix": "10.1093",
  "volume": "9",
  "author": [
    {
      "given": "Daniel G",
      "family": "Tenen",
      "sequence": "first",
    },
    etc.
  ],
  "member": "286",
  "published-online": {
    "date-parts": [
      [
        2020,
        11,
        18
      ]
    ]
  },
  "container-title": "Gastroenterology Report",
  "original-title": [],
  "language": "en",
  "score": 1,
  "resource": {
    "primary": {
      "URL": "https://academic.oup.com/gastro/article/9/1/1/5989815"
    }
  },
  "subtitle": [],
  "short-title": [],
  "issued": {
    "date-parts": [
      [
        2020,
        11,
        18
      ]
    ]
  },
  "journal-issue": {
    "issue": "1",
    "published-online": {
      "date-parts": [
        [
          2020,
          11,
          18
        ]
      ]
    },
    "published-print": {
      "date-parts": [
        [
          2021,
          3,
          16
        ]
      ]
    }
  },
  "URL": "http://dx.doi.org/10.1093/gastro/goaa066",
  "relation": {},
  "ISSN": [
    "2052-0034"
  ],
  "subject": [
    "Gastroenterology"
  ],
  "published": {
    "date-parts": [
      [
        2020,
        11,
        18
      ]
    ]
  },
  "id": "0SUohGRDV2"
}
```

Let me know if this example listed is helpful or if more information is needed.

**Comment by larsgw** [comment]
It might be the case that [`citeproc-js`](https://github.com/Juris-M/citeproc-js) cannot display the abbreviated `container-title` because that information is not available from the input data. As far as I know, `citeproc-js` does not (by default) abbreviate container titles, but does pick up the value of the `container-title-short` field (if available).
