### ISSUE TITLE
Which citation formats are available?

### ISSUE THREAD

**Issue by lightninglu10** [citation-js/citation-js#208]
I see that we can set 

```
citationObject.format("citation", {
      format: "text",
      template: "apa",
      lang: "en-US",
    });
```

but what are all the available template styles? I saw in another post the value for IEEE was "iee" (notice two e's), but when I tried "ieee" and "iee", neither used IEEE format. 

Is there something I'm missing here? Can't find in the documentation all the available template styles.

**Comment by larsgw** [comment]
The three included styles are listed in the readme of the plugin, i.e. at https://github.com/citation-js/citation-js/tree/main/packages/plugin-csl#formats. The list can also be accessed programmatically with `cslConfig.templates.list()`. Additional styles can be added as well ([docs](https://github.com/citation-js/citation-js/blob/main/packages/plugin-csl/README.md#templates)).

**Comment by larsgw** [comment]
Feel free to reopen if you have follow-up questions.
