### ISSUE TITLE
Can I change the citation key in bibtex?

### ISSUE THREAD

**Issue by HuntFeng** [citation-js/citation-js#209]
When I do extract information using doi and convert it to bibtex, the entry are always something like this
```
@article{Furtak2023supermassive,
...
}
```
Can I do customized citation key? Instead of `AuthorYearTitle`, can I define the citation key format to be `Author-Year-Title` or something else ?

**Comment by HuntFeng** [comment]
Thank you for your answer. The solution you give is helpful.

Also I'm curious, could you elaborate on why dash is unsafe?

**Comment by larsgw** [comment]
It probably isn't, but there might be some BibTeX parser that doesn't support it. But you should be able to override that.

**Comment by HuntFeng** [comment]
I see. I won't worry about that too much. My problem is solved.
