### ISSUE TITLE
Bibliography "template" parameter ignored

### ISSUE THREAD

**Issue by tristan998** [citation-js/citation-js#215]
I wrote a node js script to make citations, but changing the template does not change the citation.
` 
return cite.format('bibliography', {
        format: 'text',
        template: 'mla',/*ignored*/
        lang: 'en-US'
    });
`
The problem is also seen on [https://citation.js.org/](https://citation.js.org/), at the bottom, where the demo output always prints in APA style, regardless of the "template" value.

**Comment by larsgw** [comment]
Only a few templates are bundled in Citation.js by default. Could you try `vancouver`? It's possible to register additional templates, but I don't have the link to the docs at the moment.

**Comment by larsgw** [comment]
https://citation.js.org/api/0.7/module-@citation-js_plugin-csl.config.html#.templates

**Comment by larsgw** [comment]
I cannot reproduce this in the demo on https://citation.js.org/ with `vancouver` (and do not expect to reproduce it elsewhere). If you have any further questions please let me know.
