### ISSUE TITLE
Showing page numbers in inline citations - citeInstance.format('citation')

### ISSUE THREAD

**Issue by peterjacobson** [citation-js/citation-js#218]
### Quick overview
As per many of the styles (APA etc), if a citation is a quote or a paraphrase, the page number or some other locator must be shown in the inline citation, e.g. `(Fleiss & Sarkisyan, 2019, p. 142)`  (in APA style)

There are a few details to this that I think vary with the styles (e.g. using just the page number `(Fleiss & Sarkisyan 2019, 142)` in Chicago style, which make me either wary of rolling my own or keen to chip in to a shared solution.

Is there currently a way to do this in citation-js?

### Details
What version of Citation.js are you using? 
**0.7.1**
How are you running Citation.js (npm package, browser bundle, self-rolled bundle, webpack)? 
**In a browser bundle made with webpack**
Where are you running Citation.js? * The OS usually will not matter much, but the browser really does.
**Chrome, OSX**
**What is your input data and code?**

```js
import { Cite } from '@citation-js/core'
import '@citation-js/plugin-csl'

const citation = [
  {
    "title": "A brief review of bioluminescent systems (2019)",
    "page": 142,
    "locator": "page",
    "publisher": "Springer Science and Business Media LLC",
    "issue": "4",
    "DOI": "10.1007/s00294-019-00951-5",
    "type": "article-journal",
    "source": "Crossref",
    "prefix": "10.1007",
    "volume": "65",
    "container-title": "Current Genetics",
    "original-title": "[]",
    "language": "en",
    "score": "1",
    "subtitle": "[]",
    "short-title": "[]",
    "references-count": "61",
    "URL": "http://dx.doi.org/10.1007/s00294-019-00951-5",
    "container-title-short": "Curr Genet",
    "id": "temp_id_6787654789146775",
    ...
  }
]

const citeInstance = new Cite(citation)

const styledCitationText = citeInstance.format('citation', {
  type: "apa",
  style: "csl",
})

console.log(styledCitationText)
```

**What did you expect to happen, and what actually happened?**
```js
// Current output
// => (Fleiss & Sarkisyan, 2019)

// Desired output
// => (Fleiss & Sarkisyan, 2019, p142)
```

**What I've tried**
1. Looking through the CSL data variables and trying to add things like locator and page number to the citation object
2. Adding the options to the format method on the Cite instance

**What I wonder about**
I see that Citeproc is using citationItems, which seems to run on "locator" and "label" fields to drive that inline citation location detail. Is there a way to interface with that via citation-js's `Cite` interface?

**Note**
Thanks so much to all the contributors on this! It's working so well for us so far and I'm finding it great to use as a developer (I started using citeproc directly which was much more time-consuming and didn't have great features like the "get work data via DOI". 🙏🙏🙏

**Comment by larsgw** [comment]
Yes, there is a way to do that. First, remove `locator` and `page` from the input data (`locator` is always unused, `page` is used for the page range of an article or chapter). Second, use the `entry` option ([docs](https://citation.js.org/api/0.7/module-@citation-js_plugin-csl.output.html#.citation)):

```js
const styledCitationText = citeInstance.format('citation', {
  type: "apa",
  style: "csl",
  entry: {
    id: citeInstance.data[0].id,
    locator: 142,
    // label: 'page', // (page is default)
  }
})
```

Hope this helps.

**Comment by peterjacobson** [comment]
Amazing, thanks so much @larsgw, that's exactly what I was hoping for 🙏
