### ISSUE TITLE
Issue exporting RIS format

### ISSUE THREAD

**Issue by treecon** [citation-js/citation-js#225]
I have a citation of the following format:

```
{
  "type": "Article",
  "title": "A title",
  "author": [
    {
      "literal": "Foo, Bar"
    }
  ],
  "issued": {
    "date-parts": [
      [
        2017,
        1,
        1
      ]
    ]
  },
  "publisher": "PUBLISHER",
  "URL": "http://dx.doi.org/10.1234/publisher.999999"
}
```

The produced RIS is the following:

```
TY  - undefined
ID  - temp_id_377235137305
ER  - 
```

All the other formats that I tested (JSON, BibTex) work as expected. Any ideas? Is this a bug?
Thanks!

**Comment by larsgw** [comment]
The quick fix is that the `type` should be lowercase, `article` and not `Article`. RIS files can be very dependent on the entry type, so if it's "missing" like here it won't know how to map the fields. I'll try to improve the experience a bit more.
