### ISSUE TITLE
"process is not defined" in browser extension context (service worker)

### ISSUE THREAD

**Issue by cambraca** [citation-js/citation-js#227]
I have a browser extension on Chrome using manifest v3, and a background service worker that includes citation-js. It fails on util/fetchFile.js, on the `userAgent` line:

```
const corsEnabled = typeof location !== 'undefined' && typeof document !== 'undefined';
let userAgent = corsEnabled ? '' : `Citation.js/${pkg.version} Node.js/${process.version}`;
```

I think this is because `document` is not defined in this context, even if it's a browser and not Node (so `process` is not defined, causing the error).

There seems to be a `globalThis` top-level object in service workers, but I'm not sure what the code would look like. There's also `navigator`, which contains a `userAgent` property.

**Comment by larsgw** [comment]
Hm, I'll work on the error part. Do you happen to know if the background service worker can set the user agent?

**Comment by cambraca** [comment]
Thanks for your reply!

I tried `navigator.userAgent = "whatever"` in the console but it doesn't seem to work (not entirely sure if this is what you were asking).

In any case, there's a bigger problem when actually trying to use Cite: the XMLHttpRequest object is not available at all in service workers (they recommend switching to the Fetch API). I made a barebones extension to illustrate this: https://github.com/cambraca/manifest-v3-test-extension

See `main.js`, which runs some code using Cite, and `workaround.js`, which "mocks" that `process` var. If you run this in a browser (in Chrome, open `chrome://extensions/` and select the `build` dir using the "Load Unpacked" button), you'll see this error in the inspector for the service worker:

```
ReferenceError: XMLHttpRequest is not defined
    at u (browser.js:8:15)
    at Module.Rt (fetchFile.js:70:34)
```

(`browser.js` is from the `sync-fetch` npm package).

So, apparently it's a much bigger effort to make citation-js work inside a service worker.

**Comment by cambraca** [comment]
> Well, I'm assuming that means synchronous HTTP requests are not supported at all in service workers anymore? In that case, I would suggest using the asynchronous API:
> 
> ```js
> let example = await Cite.async('10.1038/s41467-021-25015-6')
> ```
> 
> I think that should work at least; I'll test it soon though.

For some reason, `fetch-ponyfill` still tries to use `XMLHttpRequest` and not the native `fetch`. See the latest commit on my test repo: https://github.com/cambraca/manifest-v3-test-extension/commit/f7bfd24bfba4ff0a95ceec60e4d3f6930e73cda3, it throws this error:

```
TypeError: n is not a constructor
    at fetch-browser.js:529:23
    at new Promise (<anonymous>)
    at B (fetch-browser.js:522:18)
    at Module.Ut (fetchFile.js:76:10)
```

(`n` is `XMLHttpRequest`, and looking at the stack trace, it's correctly using the `fetchFileAsync` function in `fetchFile.js`).

**Comment by larsgw** [comment]
I guess it works differently than I expected. I am running into a different issue though, I think the Node.js implementation of `fetch` _also_ overrides the `user-agent`? So I would need to use the native `fetch` in the browser when available, but not in Node.js.

**Comment by larsgw** [comment]
I've put in a workaround for now.
