### ISSUE TITLE
request: Append email to Crossref API requests

### ISSUE THREAD

**Issue by gabestein** [citation-js/citation-js#228]
Given the Crossref's API's recent instability and request that users use the "polite" API pool wherever possible (https://status.crossref.org/incidents/d7k4ml9vvswv), it would be nice to have a way to append an email address to requests to the API via citation-js.

@tefkah tried modifying https://github.com/citation-js/citation-js/blob/main/packages/plugin-doi/src/api.js locally to add an email address as both a url param and header, but both are removed from the eventual api.crossref.org request during the content negotiation process, so this seems like it might require a larger refactor.

So, I guess posting this to see if you have any ideas for how this might be accomplished. We could likely contribute if given a little direction.

**Comment by larsgw** [comment]
Thank you for the heads up, I was not aware of the situation. In general* you can set the `User-Agent` for all requests like so:

```js
const { util } = require('@citation-js/core')

util.setUserAgent('Example Foo (foo@example.org) Citation.js/0.7.11 Node.js/18.19.1')
```

There is not an option yet to set the user agent of a specific request, would that be preferable?

\* Except for in the browser, where `User-Agent` cannot be set on CORS requests as far as I know.

**Comment by gabestein** [comment]
Oh cool, thanks. We'll give this a try first and let you know if it works.

**Comment by larsgw** [comment]
Hm, Citation.js doesn't use the Crossref API directly, but uses content negotiation which redirects from `doi.org` to a variety of different APIs including Crossref and DataCite depending on the registrant (https://citation.crosscite.org/docs.html). I don't think it's possible to intercept those redirects in the browser, at least not with XHR, so I cannot consistently add the URL query either.

**Comment by gabestein** [comment]
Yup, that makes sense. We also saw that those params weren't preserved on redirect. However, we were able to achieve this (we think) by setting the user agent, as you suggested, which is preserved in redirects in our testing. Might be something to add to docs, but I don't think any change is needed.

**Comment by larsgw** [comment]
> However, we were able to achieve this (we think) by setting the user agent, as you suggested, which is preserved in redirects in our testing.

Yes, but that means neither method works in the browser. But then again, then the user's IP is used so it's less of a problem.

> Might be something to add to docs

Good point.

**Comment by gabestein** [comment]
Ah, right. We (exclusively, I think) use it on the server, so I didn't think of that. You're right that it's less of a problem for the user, but forwarding those params really should be something the DOI Foundation adds to content negotiation given Crossref's changes.
