### ISSUE TITLE
Error only in production: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by igloo1505** [citation-js/citation-js#233]
I've used your library in the past and it worked great, but now that I'm using it in a different app I'm running into the weirdest issue that appears only when running in production, even if it's still running locally.

It's in a Next@14.2.3 app, and I have an API route that calls this method:

```tsx
export const syncBib = async (appConfig: any, bibId: number = 1) => {
    const bibpath = appConfig.bibPath
    const f = new FileData(path.join(appConfig.fsRoot, bibpath))
    if(!f.exists()){
        console.warn(`Could not find a bibliography .bib file at path ${bibpath}. Your bibliography will not sync until this is resolved. Make sure to add the appropriate "bibPath" field to your appConfig.ulld.json file.`)
        return {
            errorKey: "bibPathFileDoesNotExist"
        } satisfies ErrorResponse<"bibManager">
    }
    const content = f.getContent()
    const parsed = parseBibFile(content)
    const entries = BibEntry.fromFsList(parsed.entries_raw)
    const { citations, userDefined } = getFormattedCslCitation(content, appConfig)
    let connectOrCreateEntries: Prisma.BibEntryCreateOrConnectWithoutBibInput[] = []
    const ids = citations.getIds() as string[]
    const lowerCaseIds = ids.map((x) => x.toLowerCase())
    for (const entry of entries) {
        const _args = entry.connectOrCreateArgs()
        _args.create.htmlCitation = citations.format('bibliography', {
            format: 'html',
            template: userDefined ? "user-defined" : 'apa',
            entry: entry.getIdInBibFile(ids, lowerCaseIds)
        })
        connectOrCreateEntries.push(_args)
    }
    return await prisma.bib.upsert({
        where: {
            id: bibId 
        },
        create: {
            filename: bibpath,
            entries: {
                connectOrCreate: connectOrCreateEntries
            },
            lastSync: new Date()
        },
        update: {
            filename: bibpath,
            entries: {
                connectOrCreate: connectOrCreateEntries
            },
            lastSync: new Date()
        },
        include: {
            entries: {
                include: {
                    tags: true,
                    citationGroups: true,
                    MdxNotes: {
                        select: {
                            title: true,
                            id: true,
                            href: true,
                        }
                    }
                }
            }
        }
    })
}
```

The error appears to occur here:

```tsx
     _args.create.htmlCitation = citations.format('bibliography', {
            format: 'html',
            template: userDefined ? "user-defined" : 'apa',
            entry: entry.getIdInBibFile(ids, lowerCaseIds)
        })
```

I am getting back the proper id in that `getIdInBibFile` method, and the `user-defined` model is applied in the `getFormattedCslCitation` function that looks like this:

```tsx
import "@citation-js/plugin-csl";
import "@citation-js/plugin-bibtex";
import Cite from "citation-js";
import path from "path";
import { AppConfigSchemaOutput } from "@ulld/configschema/types";
import { FileData } from "@ulld/utilities/fileClass";

export const getFormattedCslCitation = (
    content: string,
    appConfig: AppConfigSchemaOutput,
) => {
    let useUserDefined = false;
    if (appConfig.cslPath) {
        let f = new FileData(path.join(appConfig.fsRoot, appConfig.cslPath), false);
        if (f.exists()) {
            const cslFileContent = f.getContent();
            if (cslFileContent) {
                let config = Cite.plugins.config.get("csl");
                if(config){
                    useUserDefined = true;
                    config?.templates.add("user-defined", cslFileContent);
                } else {
                    console.error("Could not gather csl config. Cannot parse citations with user provided csl format.")
                }
            }
        }
    }
    let citations = new Cite(content);
    return { citations, userDefined: useUserDefined };
};
```

This all works flawlessly in development, but I've spent 3 days now working on this error. This is the complete output here:
Don't judge me for my home directory.

```tsx
TypeError: Cannot read properties of undefined (reading 'name')
    at t.XmlJSON.addMissingNameNodes (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:17:43244)
    at new t.Engine (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:17:67469)
    at u (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:1:373946)
    at c (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:1:374213)
    at bibliography (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:1:374923)
    at tl (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:1:28027)
    at g.tm [as format] (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:1:28107)
    at d (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/chunks/34354.js:17:2746)
    at async v (/Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/.next/server/app/api/events/onSync/route.js:1:12672)
    at async /Users/bigsexy/Desktop/current/ulldSandbox/ulldApp/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
```

Since the `addMissingNameNodes` appears to be a part of the csl plugin, and the only references I could find to it came from the APA csl content that citation-js provides, I tried this with the provided APA style, the provided `harvard1` style, and a csl file of my own that generates the AIP citation style. Both the AIP and the APA style work fine in development, but in production they fail with the above error. I didn't test the Harvard style in development, or the Vancouver style in either development or production.

I've also tried applying the 'force-dynamic' status to the API route which is more Next specific, but still no luck.

### If you want to look at the project

There are two projects on my profile, one is a large monorepo called `ulld`, and the other a small React/Next application that utilizes most of the monorepo, `ulldApp`. The app is generated by a build script to populate most of the useful bits, but you should be able to test the API route without running the build script, although it will require a file called `appConfig.ulld.json` at the root of the project that looks something like [this](https://github.com/user-attachments/files/16680978/appConfig.ulld.json) to not blow up.

Thanks, and this is an awesome library regardless. 

If there's any other information that might help, please let me know. I've been working on this project for 6+ months, and I'm a week away from wrapping it up but this bug is the single thing getting in the way of the last little bit of tidying up that I need to do and it's driving me insane.

The versions look like this:

| Package | Version | 
| -------- | -------- |
|`@citation-js/plugin-csl` | 0.7.14 |
| `@citation-js/plugin-bibtex` | 0.7.14 |
| `citation-js` | 0.7.15 (tried 0.7.14 as well) |

**Comment by larsgw** [comment]
Thank you for the report. The error occurs in the `citeproc-js` dependency, the csl plugin is mostly a wrapper around that dependency. There was a similar issue with Next.js producing errors in `citeproc-js` code last year as well (#194), I will have to investigate.

**Comment by larsgw** [comment]
I think I might be able to figure it out a bit quicker if you could send `ulldApp/.next/server/chunks/34354.js` (that way I don't have to set up the build process myself), but I will take a look regardless.

**Comment by larsgw** [comment]
I was able to set up a minimal example myself, so I don't need the file anymore.

**Comment by larsgw** [comment]
Could you try Next.js v15.0.0-canary.121? Or are there too many breaking changes to try?

**Comment by larsgw** [comment]
Looks like `swc` is optimizing a function like the following (it's `parseXml`):

```js
function foo (arg) {
    const a = { b: [] }
    const c = [a.b]
    c[0].push(arg)
    return a.b[0]
  }
```

into the useless

```js
function foo (n) {
  return [[]][0].push(n),
  [][0]
}
```

But I think it has been fixed in a recent update, as with the canary v15 it produces

```js
function(e) {
  let n = [];
  return [n][0].push(e),
  n[0]
}
```

**Comment by larsgw** [comment]
Oh lol the bug report in swc actually mentioned Citation.js as well https://github.com/swc-project/swc/pull/8956

**Comment by igloo1505** [comment]
I can try it with Next 15. There are quite a few moving pieces in the generated app that don't appear in the template so it might introduce some issues, but right now my biggest concern is citation-js. If you took a look at my bio it kind of describes how this app came to be, and in the original app that isn't generated from a config file citation-js works flawlessly. It's `citation-js@0.6.8`, `@citation-js/plugin-csl@0.6.8` and `@citation-js/plugin-bibtext@0.6.8` in that app, and `next@14.0.4`. I tried using those citation-js related versions in the current app and still had the same issue, but I'll give this a shot with `next@15.x.x`. It wouldn't even be the end of the world to move back to 14.0.4 if it gets this to work.

**Comment by igloo1505** [comment]
## Update

Thanks so much for looking at this so quickly. Once you narrowed it down to swc, I was able to disable swc with `swcMinify: false` in the `next.config.mjs` file. I didn't attempt to build with `next@15.x.x` because it requires `react@19.x.x` which would introduce quite a few issues and I wasn't sure if that would even be successful, but in `next@15.x.x` the `swcMinify` option will be removed entirely and be forced to be true.

**Comment by larsgw** [comment]
> in `next@15.x.x` the `swcMinify` option will be removed entirely and be forced to be true according to some comments in their code.

Oh wow, I didn't realise that. That seems like a bad idea given how many issues there seem to be.

**Comment by igloo1505** [comment]
I created another issue [here](https://github.com/vercel/next.js/issues/69150#issue-2478504296) if you want to keep track of it, just to let them know about the issue with swc since they seem to be kind of aware that forcing people to use swc might introduce a lot of issues.
