### ISSUE TITLE
explore the impact of the WDQS graph split

### ISSUE THREAD

**Issue by egonw** [citation-js/citation-js#235]
[citation.js is affected](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service/WDQS_graph_split/Affected_tools) and there are [three places where WDQS is used](https://github.com/search?q=org%3Acitation-js+query.wikidata&type=code).

This issue will report observed impact.

**Comment by egonw** [comment]
For this query:

https://github.com/citation-js/citation-js/blob/ef9aaff434cb97034ccbd94bdc7557d5e2c1926f/scripts/types.wikidata.js#L8-L18

It looks like this returns the same entries for `books` and `scholarly articles` for `query` and `query-main`. I think this one can run on `query-main`. Since `query-main` will become the future `query`, this code does not need to be changed. But it assumes, which I believe is the intention, that the `scholarly article` class hierarchy will always be in the main graph.

**Comment by egonw** [comment]
@larsgw,  think we need to talk. Obviously, somewhere in the code it needs to use `query-scholarly`, but I am not sure where. Not in the above code, but obviously elsewhere.

**Comment by larsgw** [comment]
The scholarly graph seems to include Q13442814, but surely that had subclasses? Also, if the subclass chain is broken somewhere in the middle how do you query for that?

The rest of the code primarily uses wbgetentities of the MediaWiki API which AFAIK will not change. I do think the quickstatement plugin uses SPARQL though.

**Comment by egonw** [comment]
Okay, since that was the only place, I think it can be closed.
