### ISSUE TITLE
Error when exporting to RIS

### ISSUE THREAD

**Issue by rmzelle** [citation-js/citation-js#238]
Hi, I'm trying to update https://github.com/rmzelle/ref-extractor from a rather ancient citation-js v0.4.0-10 to the latest v0.7.15, but I'm flummoxed by an error I get when I try to format as "ris". Other formats work fine ("data", "bibtex", "bibliography"). Any idea what could be wrong?

My JavaScript code:

```
var Cite = require('citation-js')
var edited_json = JSON.stringify(JSON.parse(csl_json).map(c => {
          c.note = c.note.replace(/Times cited: \d+\n/g, '');
          if (c.note == "") { c.note = undefined; }
          return c;
        }));
var citationRender = new Cite(edited_json);
renderedOutput = citationRender.format(outputFormat); 
```

The error:

> citation.min.js:1 Uncaught Error: Failed to convert id to ID
>     at _loop (citation.min.js:1:135546)
>     at citation.min.js:1:135790
>     at citation.min.js:1:454260
>     at Array.map (<anonymous>)
>     at exports.format (citation.min.js:1:454233)
>     at exports.format (citation.min.js:1:104229)
>     at exports.format (citation.min.js:1:2446)
>     at convertOutput (ref-extractor.js:529:41)
>     at HTMLSelectElement.handleFormatSelect (ref-extractor.js:27:49)Caused by: TypeError: id.slice is not a function
>     at Object.toSource (citation.min.js:1:449003)
>     at _loop (citation.min.js:1:135448)
>     at citation.min.js:1:135790
>     at citation.min.js:1:454260
>     at Array.map (<anonymous>)
>     at exports.format (citation.min.js:1:454233)
>     at exports.format (citation.min.js:1:104229)
>     at exports.format (citation.min.js:1:2446)
>     at convertOutput (ref-extractor.js:529:41)
>     at HTMLSelectElement.handleFormatSelect (ref-extractor.js:27:49)

**Comment by rmzelle** [comment]
I got the same error on https://citation.js.org/demo/ with https://gist.github.com/rmzelle/2d8c899a629617f9c433bca3219f630d (the input was CSL JSON extracted from a Word document), and it looks like citation-js did not appreciate the "id" field in the JSON. Removing this field (https://gist.github.com/rmzelle/76c4c06b84e97e15a552798a439e7991) fixes the error (at least at https://citation.js.org/demo/ where I just tested this).

**Comment by rmzelle** [comment]
Ah, it looks like the error occurs when "id" is numeric, and not when "id" is a string. From what I can tell "id" is allowed to be either according to the CSL JSON spec:

https://github.com/citation-style-language/schema/blob/e3ce254a72c4470a5ed3b9d23b428017d25674e9/schemas/input/csl-data.json#L59-L61

Doesn't work:

```
[
  {
    "id": 255,
    "type": "patent",
```

Works:

```
[
  {
    "id": "one",
    "type": "patent",
 ```

**Comment by rmzelle** [comment]
I also found https://github.com/citation-js/citation-js/pull/139 but the fix implemented there seems specific to the bibtex plugin.

**Comment by larsgw** [comment]
Thank you!

**Comment by rmzelle** [comment]
@larsgw, thanks for the quick fix and new release!
