### ISSUE TITLE
BibTeX export: but edition into {..}

### ISSUE THREAD

**Issue by nichtich** [citation-js/citation-js#27]
Edition numbers may not be simple numeric. I have an edition number `1.56` which is exported as `edition=1.56` in BibTeX, causing an error. Export as `edition={1.56}` solves the issue.

**Comment by larsgw** [comment]
Thanks, I didn't know they couldn't be floating-point numbers* but I guess that makes sense. Is there any reason not to always use brackets, even when it *is* numeric?

\* I understand that may not be the meaning of `1.56` in this case, but that's why the bug is happening.

**Comment by nichtich** [comment]
Better always use braces for all fields, see https://tex.stackexchange.com/a/109066/1044
