### ISSUE TITLE
Bibtex Label Generation fails on titles with " character

### ISSUE THREAD

**Issue by isTravis** [citation-js/citation-js#35]
[This line](https://github.com/citation-js/citation-js/blob/master/packages/plugin-bibtex/src/output/label.js#L31) causes citation entries whose title has a `"` character to crash. You can verify this by running the following in your console and observing the error:

```
var str = '"Bugs": a never ending story';
str.match(/^(?:(?:the|a|an)\s+)?([^@{}"=,\\\s]+)/i)[1]
```

**Comment by larsgw** [comment]
Fair enough lol, didn't think of that. Something like this then?

```js
str.split(/\W+/).find(word => word.length && !['the', 'a', 'an'].includes(word))
```

Probably a lot more readable too.

**Comment by isTravis** [comment]
(Apologies - just realized my original link was broken - fixed now.)

Thanks so much for the quick response. That solution does feel much more readable and would certainly solve my use case. 👍
