### ISSUE TITLE
Handle single keywords

### ISSUE THREAD

**Issue by larsgw** [citation-js/citation-js#67]
## Problem

When a RIS entry has multiple tags of a single kind (like multiple `AU` or `KW`) the parser automatically puts the values in an array. However, the parser does not know to do this if only a single `AU` or `KW` is present. The converter for `AU` takes this into account, the converter for `KW` does not.

## Solution

Account for the fact that `words` could be a string in the following line of code:

https://github.com/citation-js/citation-js/blob/ec3caf160ab87d0ec42bf33fe0119058c957737c/packages/plugin-ris/src/converters.js#L58

You can look at how the `AU` converter handles this:

https://github.com/citation-js/citation-js/blob/ec3caf160ab87d0ec42bf33fe0119058c957737c/packages/plugin-ris/src/converters.js#L36

**Comment by anusha5695** [comment]
Hi I would like to work on this issue
