### ISSUE TITLE
[plugin-wikidata]: support configuration of language(s)

### ISSUE THREAD

**Issue by nichtich** [citation-js/citation-js#7]
The language `'en'` is hard-coded at several places:

* https://github.com/citation-js/citation-js/blob/113776d8b373284f4484c33bfaf13bb78de146f0/packages/plugin-wikidata/src/json.js#L31
* https://github.com/citation-js/citation-js/blob/113776d8b373284f4484c33bfaf13bb78de146f0/packages/plugin-wikidata/src/list.js#L19

It should be configurable to get titles, author names etc. from Wikidata in other languages.

**Comment by nichtich** [comment]
There is also a related bug [here](https://github.com/citation-js/citation-js/blob/113776d8b373284f4484c33bfaf13bb78de146f0/packages/plugin-wikidata/src/json.js#L92) that makes the importer crash if no English label exists (common for non-English publications).

**Comment by larsgw** [comment]
Refactoring the entire plugin now. Do you think it should fall back on `'en'`?

**Comment by larsgw** [comment]
Here you go! Configure with

```js
const wdConfig = Cite.plugins.config.get('wikidata')
wdConfig.langs // ['en']
wdConfig.langs.unshift('de') // ['de', 'en']
```

So you can specify the exact fallback route (there's no "any" fallback yet).

**Comment by larsgw** [comment]
There's [documentation](https://github.com/citation-js/citation-js/tree/master/packages/plugin-wikidata#configuration) (not much, but it's there), tests and a fix for a spot I missed now.

**Comment by nichtich** [comment]
Thanks! I failed to test because my `Cite.plugins.config.get('wikidata')` is `undefined` as I failed to include the current development version (the splitting into sub-modules confuses me). An "any" fallback (maybe `*`) could result in overly large result sets because you cannot directly query for "just one language" only "all languages".

**Comment by larsgw** [comment]
> the splitting into sub-modules confuses me

Yeah, that may have been a mistake. `@citation-js/core` has nothing (apart from JSON & some other generic stuff; `citation-js` is the same as it was before splitting everything up.

> I failed to test because my `Cite.plugins.config.get('wikidata')` is `undefined`

I noticed that too but forgot to report back, it's `Cite.plugins.config.get('@wikidata')`. Cause: some legacy stuff, I probably thought `@` signs were cool 1-2 years ago.
