### ISSUE TITLE
SyntaxError: Escape sequence not recognized

### ISSUE THREAD

**Issue by pussiatoday** [citation-js/citation-js#81]
```
{\textbar}
{\textless}
{\textgreater}
```

Duplicate of https://github.com/larsgw/citation.js/issues/194

**Comment by larsgw** [comment]
This issue should be fixed in `v0.5.0-alpha.10`. If not, please re-open the issue.

**Comment by pussiatoday** [comment]
![Yay!](https://media2.giphy.com/media/xUPGchCDuw3WnREEKc/giphy.gif)
