### ISSUE TITLE
bibtex case sensitive tags

### ISSUE THREAD

**Issue by AWehrhahn** [citation-js/citation-js#85]
Bibtex/text doesn't parse uppercase tags correctly.
Example:
`Cite.input('@article{test, Author = "test"}')`

creates a bibtex citation without the author field, whereas

`Cite.input('@article{test, author = "test"}')`

works as expected.

**Comment by afnan** [comment]
Yes this is strange. I used the following to take care of it before passing the string 

` stringVar.replace(/Abstract =/g, "abstract =")
            .replace(/Author =/g, "author =")
            .replace(/Title =/g, "title =")
            .replace(/Year =/g, "year =")
            .replace(/= {{/g, "= {")
            .replace(/}},/g, "},");`

**Comment by larsgw** [comment]
This issue should be fixed in `v0.5.0-alpha.10`. If not, please re-open the issue.
