### ISSUE TITLE
Bump built-in APA CSL for plugin-csl to 7th edition

### ISSUE THREAD

**Issue by gabestein** [citation-js/citation-js#88]
The current [built-in APA CSL](https://github.com/citation-js/citation-js/blob/113776d8b373284f4484c33bfaf13bb78de146f0/packages/plugin-csl/src/styles.json) is for the 6th edition, which is out of date as of [October 2019](https://www.scribbr.com/apa-style/apa-seventh-edition-changes/). The new edition includes a number of very noticeable changes, like using et al. for inline citations after 2 authors instead of 5, formatting DOIs as URLs, removing "retrieved from" from URLs, etc.

There is an updated [7th Edition csl](https://github.com/citation-style-language/styles/blob/master/apa.csl), published by zotero, in the Citation Style Language github repo.

I'd be happy to submit a quick PR if you'd like, but wanted to make sure there wasn't some kind of reasoning for not doing so before that, because we could just manually add the APA 7th edition from the CSL repo if needed (also, it seems simple enough that it may not be worth it to have me submit).

**Comment by larsgw** [comment]
The main reason I haven't done this yet is because I was planning on storing a JSON representation of the style instead of XML, but I can keep that idea for another major version change. A PR would be good actually, could you base it off the `v0.5` branch? Given the noticeable changes I think I will bundle it as a major change (probably `v0.5.0-alpha.6` then).

**Comment by gabestein** [comment]
Thanks, will do! Likely tomorrow morning (US Eastern), but it's possible I'll be able to get to it tonight.

Also: even though I do think fast-tracking change makes sense given that I've now seen the 7th in the wild quite a bit, I love the idea of being able to represent styles in JSON, in general. Especially if there was an XSLT or some other way of converting any given CSL from XML to JSON. Probably beyond the scope of what you're planning, but, maybe some day!

**Comment by larsgw** [comment]
Well, citeproc-js always parses the XML into an internal (JSON) structure and can load it directly as that as well. I meant to basically skip the step of parsing XML with an old (custom?) parser each time. I am not entirely sure about exporting the JSON though, and it would change the API for adding your own templates a bit (parse XML on add I suppose).
