### ISSUE TITLE
Handling missing references

### ISSUE THREAD

**Issue by ezzaouia** [citation-js/citation-js#93]
This issue is more related to citeproc, but I decided to open it here. As I only played with _**citation-js**_ this weekend,  there might be a solution that I couldn't find in the documentation.

**Issue**:
When we try to output a citation that does not exist in our input references, a `SyntaxError: Unexpected token u in JSON at position 0` is fired.
I guess **_citeproc_** tries to retrieve a reference like so:

`Item = JSON.parse(JSON.stringify(this.sys.retrieveItem("" + id)));` 

However, in case of an `undefined` `JSON.parse( .. )` fires Uncaught SyntaxError.

**Wanted behavior**:
If a reference is missing, it would be nice to output question marks, i.e., **??**.

**Example**:
- This works

```js
let Cite = require("citation-js");

let cite = new Cite( [ { id: 1, title: 'ref1' }, { id: 2, title: 'ref2'  } ] );

const opt = { format: "html", template: "apa", lang: "en-US"};

let citation = cite.format("citation", {
  entry: [ 1, 2 ],
  opt,
});

console.log( citation );

// Output
// (“ref1,” n.d.-a; “ref2,” n.d.-b) 
```
- This doesn't work

```js
let citation = cite.format("citation", {
  entry: [ 1, 2, 3 ],
  opt,
})

// Output
// SyntaxError: Unexpected token u in JSON at position 0 
```
- Wanted output
```
(“ref1,” n.d.-a; “ref2,” n.d.-b; ??) 
```

MWE: [Codesandbox](https://codesandbox.io/s/mystifying-rgb-ihfq3?file=/src/index.js)

**Comment by larsgw** [comment]
Since citation-js does not control the citeproc-js output it would be a bit difficult to prescribe `??` as the output for unknown references, but it could avoid the error internally by passing an empty object if no reference is found (probably rendering `n.d.`). The CSL plugin is the next one on the list to get a rework if all goes well, so I can improve the process a bit there.

**Comment by ezzaouia** [comment]
Thank you @larsgw for your replay.
Yeah, using a dummy (empty) object outputs `n.d.`.

**Comment by larsgw** [comment]
To avoid unexpected output I am going to clarify the error message ("Cannot find entry with id '...'") instead of outputting a placeholder.
