### ISSUE TITLE
documentation references Cite.plugins.output.config which is undefined

### ISSUE THREAD

**Issue by nitaro** [citation-js/citation-js#96]
Hello,

The documentation at https://citation.js.org/api/tutorial-output_plugins_csl.html
has 2 references to `Cite.plugins.output.config` for adding new templates:

    Cite.plugins.output.config.get('csl')
    config.templates.add(templateName, template)

But `Cite.plugins.output.config` is `undefined`.

I think the most current syntax is instead the following?

    Cite.CSL.register.addTemplate(templateName, template);

I experience this behavior with versions 0.4.10 and 0.5.0-alpha.6.

thank you,

**Comment by larsgw** [comment]
`Cite.plugins.output.config` is a typo I still need to fix. Your options (depending on which npm package you use):

```js
const { Cite, plugins } = require('@citation-js/core')

// Instead of plugins.output.config, plugin.config
const config = plugins.config('csl')
config.templates.add(templateName, template)
```

or

```js
const Cite = require('citation-js')

// Instead of Cite.plugins.output.config, Cite.plugin.config
const config = Cite.plugins.config('csl')
config.templates.add(templateName, template)

// Or the old, deprecated method
Cite.CSL.register.addTemplate(templateName, template)
```

**Comment by Aton-Kish** [comment]
In the version 0.5.0-alpha.7, I think the following is correct:
```js
const { Cite, plugins } = require("@citation-js/core")

const config = plugins.config.get("@csl");
config.templates.add(templateName, template)
```
or
```js
const Cite = require('citation-js')

const config = Cite.plugins.config.get("@csl");
config.templates.add(templateName, template)

// or
Cite.CSL.register.addTemplate(templateName, template)
```

**Comment by khoivan88** [comment]
> In the version 0.5.0-alpha.7, I think the following is correct:
> 
> ```js
> const { Cite, plugins } = require("@citation-js/core")
> 
> const config = plugins.config.get("@csl");
> config.templates.add(templateName, template)
> ```
> 
> or
> 
> ```js
> const Cite = require("citation-js")
> 
> const config = Cite.plugins.config.get("@csl");
> config.templates.add(templateName, template)
> 
> // or
> Cite.CSL.register.addTemplate(templateName, template)
> ```

THANK YOU SOOO MUCH for sharing this. I was about to give up on this until I found your solution!!!

**Comment by larsgw** [comment]
Sorry for all the confusion. I am glad you found a solution in the end. Updated documentation is available at https://github.com/citation-js/citation-js/tree/v0.5/packages/plugin-csl at the moment.

**Comment by khoivan88** [comment]
@larsgw Thank you for this very nice package. It does save me a lot of time building a new academic website without having to tediously make the citation in HTML format!
